(function(g){var window=this;var k2=function(a){var b={languageCode:a.i,languageName:a.l,displayName:g.zz(a),kind:a.o,name:a.u,id:a.H,is_servable:a.C,is_default:a.isDefault,is_translateable:a.D,vss_id:a.A};a.g&&(b.translationLanguage=a.g);return b},l2=function(a){return a.g?a.g.languageCode:a.i},zpa=function(a,b){var c=new g.yz;
c.i=a.i;c.l=a.l;c.u=a.u;c.o=a.o;c.isDefault=!1;c.C=a.C;c.D=a.D;c.A=a.A;c.F=a.F;c.g=b;return c},m2=function(a){if(!Apa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(Bpa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]},Cpa=function(){this.i=[];
this.g=[]},n2=function(a,b){return b?a.g.concat(a.i):a.g},o2=function(a,b){switch(b.o){case "asr":var c=a.i;
g.Xa(c,(0,g.x)(b.Lq,b))||c.push(b);break;default:c=a.g,g.Xa(c,(0,g.x)(b.Lq,b))||c.push(b)}},p2=function(){g.B.call(this);
this.i=new Cpa;this.u=[]},q2=function(a,b,c){p2.call(this,a);
this.g=null;this.u=b.pu;this.l=c},r2=function(){this.Ta=[]},s2=function(a,b,c,d,e,f){g.B.call(this);
this.I=a;this.l=b;this.A=new r2;this.g=null;this.F=d;this.P=f;this.i=this.o=null;this.D=c;this.C=e||!1;this.H=new g.K(this.Iw,1E3,this);g.D(this,this.H);this.u=new g.zs(this);g.D(this,this.u);g.P(g.W(b).experiments,"html5_disable_captions_seek_complete")?this.u.K(b,"seekto",this.qx):this.u.K(b,"seekcomplete",this.OF);this.qx(b.getCurrentTime());this.Iw()},t2=function(a,b){b-=a.l.Ib();
var c=a.g;a.g=g.Va(a.D.wf(b).g);c!=a.g&&a.P&&a.P()},u2=function(a,b){var c=g.xv(g.Hv(b,a.I,{})),d={format:"RAW",
withCredentials:!0};a.C&&(d.responseType="arraybuffer");a.i=g.ir(c,d,3,100).then((0,g.x)(a.wK,a));a.o=b;c=a.A;d=a.o.g[0].i;var e=g.ob(c.Ta,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.Ta[e-1]&&e<c.Ta.length&&1==c.Ta[e]-d?(g.bb(c.Ta,e),g.bb(c.Ta,e-1)):0<e&&1==d-c.Ta[e-1]?c.Ta[e-1]=d:e<c.Ta.length&&1==c.Ta[e]-d?c.Ta[e]=d:(g.kb(c.Ta,e,0,d),g.kb(c.Ta,e+1,0,d)))},v2=function(a,b){p2.call(this,g.W(b));
this.g=a;this.C=b;this.l=null;this.o=!1;this.A=g.hz(g.W(this.C))&&!this.g.i},w2=function(a,b){var c=[],d;
for(d in a.g.g){var e=a.g.g[d];if(g.XU(e,b||null)){var f="en",k="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;c.push(new g.yz({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},Dpa=function(a,b){return null!=b&&b in a.g.g?a.g.g[b]:null},x2=function(a,b,c){var d=[],e;
for(e in a.g.g){var f=a.g.g[e];if(g.XU(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode==b&&d.push(f)}}return d.length?d[0]:null},y2=function(a,b,c,d,e){p2.call(this,e||null);
c=c||g.pq(a).hl||"";c=c.split("_").join("-");this.o=g.rq(a,{hl:c});this.l=b;this.A=!!d;this.C={};this.g=null},z2=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.SD.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.l=f;this.g=k},A2=function(a,b,c,d,e){g.SD.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.g=[]},C2=function(a){a=void 0===a?{}:a;
var b="_"+B2++;return new A2(0,0x8000000000000,0,b,a)},E2=function(a,b,c,d,e,f){var k={};
g.Sa(k,b);g.Sa(k,a.params);g.Sa(k,c);var l={};g.Sa(l,b.wb);a.params.wb&&g.Sa(l,a.params.wb);g.Sa(l,c.wb);k.wb=l;g.V.call(this,{B:"div",G:"caption-window",L:{id:"caption-window-"+a.id,dir:1==k.ze?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},J:[{B:"span",G:"captions-text",L:{style:"word-wrap: normal; display: block;"}}]});this.C=[];this.O=!1;this.o=a;this.V=this.R=null;this.Pa=e;this.Ma=f;this.D=null;this.X=.96*e;this.wa=.96*f;this.l=k;this.Ia=c;this.A=this.i["captions-text"];this.Ba=
null!=this.A.style["box-decoration-break"]||null!=this.A.style["-webkit-box-decoration-break"];this.Z=d/360*16;this.type=0;this.ka=this.Z*D2(l);a=new g.Fs(this.element,!0);g.D(this,a);a.subscribe("dragstart",this.NF,this);a.subscribe("dragmove",this.MF,this);a.subscribe("dragend",this.LF,this);this.va=this.ma=0;b="";this.l.windowOpacity&&(a=m2(this.l.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.l.windowOpacity+")");a={"background-color":b,display:!1===this.l.isVisible?"none":"","text-align":Epa[this.l.textAlign]};
this.Ba&&(a["border-radius"]=b?this.ka/8+"px":"");if(this.u=2==this.o.params.ze||3==this.o.params.ze)b=this.element,c="vertical-rl",1==this.l.vA&&(c="vertical-lr"),g.Ld&&(c="vertical-lr"==c?"tb-lr":"tb-rl"),g.Ah(b,"-o-writing-mode",c),g.Ah(b,"-webkit-writing-mode",c),g.Ah(b,"writing-mode",c),g.Ah(b,"text-orientation","upright"),g.I(b,"ytp-vertical-caption"),3==this.o.params.ze&&(g.Ah(b,"text-orientation",""),g.Ah(b,"transform","rotate(180deg)"));g.Ah(this.element,a);switch(this.l.Uf){case 0:case 1:case 2:g.I(this.element,
"ytp-caption-window-top");break;case 6:case 7:case 8:g.I(this.element,"ytp-caption-window-bottom")}},D2=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0==a.offset||2==a.offset)b*=.8;return b},F2=function(a,b){var c={},d=b.background?b.background:a.l.wb.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.l.wb.backgroundOpacity;d=m2(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Ba&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ka/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Z*D2(b)+"px";d=1;e=b.color||a.l.wb.color;if(b.color||null!=b.textOpacity)e=m2(e),d=null==b.textOpacity?a.l.wb.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.yu&&(k=e=b.yu);var l=a.Z/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;q<=r;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(q=0;5>q;q++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.Rq()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.l.wb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Re&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");
b.MD&&(c.visibility="hidden");1==b.OD&&a.u&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.jz||g.kz,3==a.o.params.ze?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1==b.ye||2==b.ye||3==b.ye||4==b.ye||5==b.ye)if(g.jz)c["font-weight"]="bold";else switch(c["text-emphasis"]="filled circle",c["webkit-text-emphasis"]="filled circle",b.ye){case 4:case 3:c["text-emphasis-position"]="under right";c["webkit-text-emphasis-position"]="under right";break;
case 5:case 2:c["text-emphasis-position"]="over left",c["webkit-text-emphasis-position"]="over left"}return c},G2=function(a){a.D=g.Rd("SPAN");
g.Ah(a.D,{display:"block"});g.I(a.D,"caption-visual-line");a.A.appendChild(a.D)},H2=function(a,b){var c=g.Rd("SPAN");
g.Ah(c,{display:"inline-block","white-space":"pre-wrap"});g.Ah(c,F2(a,b));c.classList.add("ytp-caption-segment");a.D.appendChild(c);c.previousElementSibling&&(g.Ah(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Ah(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},I2=function(a,b,c){a.O=a.O||!!c;
var d={};g.Sa(d,a.l.wb);g.Sa(d,c||b.g);g.Sa(d,a.Ia.wb);(c=!a.D)&&G2(a);for(var e=a.R&&a.V&&g.ac(d,a.V)?a.R:H2(a,d),f=g.Ea(b.text),k=f?b.text.split("\n"):[b.text],l=0;l<k.length;l++){var m=0<l||!b.l,n=k[l];m&&!c?(G2(a),e=H2(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Sd(n):n),f||"RUBY"!=n.tagName||4!=n.childElementCount||g.jz||!g.Eh(n.children[2],"text-emphasis")||(m=a.u?"padding-right":"padding-top",g.Eh(n.children[2],"text-emphasis-position")&&(m=a.u?"padding-left":"padding-bottom"),g.Nd?g.Ah(e,m,"1em"):
g.Ah(e,m,"0.5em")))}a.V=d;a.R=e;a.C.push(b)},J2=function(){},L2=function(){this.o=this.i=this.mode=this.l=0;
this.u=new K2(this);this.A=new K2(this);this.g=[];this.clear()},Fpa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{El:a,
Fl:b,result:0};a=M2[a];b=M2[b];if(a&128){if(!(b&128)&&0!=c.g&&c.i==b)return{El:a,Fl:b,result:1}}else if(b&128&&1<=a&&31>=a)return{El:a,Fl:b,result:2};return{El:a,Fl:b,result:3}},Gpa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.o&&a.reset(),a.u.g.clear(),a.A.g.clear()):(a.o=0,N2(a.u,b,c,d))},Hpa=function(a,b){a.g.sort(function(e,f){var k=e.time-f.time;
return 0==k?e.order-f.order:k});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.i=d.time;0==d.type?Gpa(a,d.ru,d.tu,b):1==d.type&&a.l&496&&N2(a.A,d.ru,d.tu,b)}a.g.length=0},O2=function(){this.g=0},P2=function(){this.i=this.l=this.g=0},Q2=function(){this.timestamp=this.Qd=0},R2=function(a){this.l=[];
for(var b=0;15>=b;b++){this.l[b]=[];for(var c=0;32>=c;c++)this.l[b][c]=new Q2}this.g=this.i=this.row=0;this.style=new O2;this.u=a;this.o=0},S2=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.u.i+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var r=a.l[m][q];
if(0!=r.Qd){0==c&&(c=m,d=q);n=String.fromCharCode(r.Qd);var u=r.timestamp;u<e&&(e=u);r.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==r.Qd||32==q)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.u(c,d,e,l,f)}else for(d=c=0,f=e=a.u.i+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(q=a.l[k][m],r=q.Qd,0!=r&&(0==c&&(c=k,d=m),n=String.fromCharCode(r),u=q.timestamp,u<=e&&(e=u),l+=n,q.reset()),32==m||0==r)l&&b.u(c,d,e,f,l),e=f,l="",d=c=0},Mpa=function(a,b){switch(a){case 0:return Ipa[(b&127)-32];
case 1:return Jpa[b&15];case 2:return Kpa[b&31];case 3:return Lpa[b&31]}return 0},T2=function(a){return a.l[a.row][a.i]},U2=function(a,b,c){2<=b&&1<a.i&&(--a.i,T2(a).Qd=0);
var d=T2(a);d.timestamp=a.u.i+0;d.Qd=Mpa(b,c);32>a.i&&a.i++},V2=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.l[b+e][f].fg(a.l[c+e][f])},W2=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.l[b+d][e].reset()},X2=function(a){a.row=0<a.g?a.g:1;
a.i=1;W2(a,0,15)},Y2=function(a){this.o=a;
this.u=0;this.style=new O2;this.A=new R2(a);this.C=new R2(a);this.D=new R2(a);this.i=this.A;this.l=this.C;this.g=this.i},Z2=function(a,b,c){var d=a.i,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:S2(d,c),X2(a.i),X2(a.l),d.row=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.o.mode=1<<d.o;e?d.i=1:d.g!=b&&(d.g>b?(S2(d,c),W2(d,d.row-d.g,b)):d.row<b&&(b=d.g),d.g=b)},$2=function(a){a.style.set(1);
a.g=a.l;a.g.g=0;a.g.style=a.style;a.o.mode=1<<a.g.o},a3=function(a){a.style.set(4);
a.g=a.D;a.g.style=a.style;a.o.mode=1<<a.g.o},K2=function(a){this.i=a;
this.g=new P2;this.u=0;this.l=new Y2(a);this.A=new Y2(a);this.o=this.l},N2=function(a,b,c,d){a.g.update();
b=Fpa(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.El;c=b.Fl;if(32<=e||!e)a.i.mode&a.i.l&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.o.g,b&96&&U2(a,0,b),c&96&&U2(a,0,c),0!=b&&0!=c&&3==a.style.g&&S2(a,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.l=e,b.i=c,b.g=2,b=e&8?a.A:a.l,a.o=b,a.i.mode=1<<(a.u<<2)+(b.u<<1)+(4==b.style.g?1:0),(a.i.mode|1<<(a.u<<2)+(b.u<<1)+(4!=b.style.g?1:0))&a.i.l))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.g;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.g&&(d=c.g,d==c.row))break;var f=1+c.row-c.g,k=1+d-c.g;V2(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));W2(c,b,e)}}c.row=d;c.i=a+1}else switch(e&7){case 1:switch(c&112){case 32:U2(b.g,0,32);break a;case 48:57==c?(d=b.g,T2(d).Qd=0,32>d.i&&d.i++):U2(b.g,1,c&15)}break;case 2:c&32&&U2(b.g,2,c&31);break;case 3:c&32&&U2(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:$2(b);break;case 33:d=
b.g;1<d.i&&(--d.i,T2(d).Qd=0);break;case 36:d=b.g;b=T2(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.l[a][c]==b){for(;32>=c;c++)d.l[a][c].reset();break}break;case 37:Z2(b,2,d);break;case 38:Z2(b,3,d);break;case 39:Z2(b,4,d);break;case 40:U2(b.g,0,32);break;case 41:b.style.set(2);b.g=b.i;b.g.g=0;b.g.style=b.style;b.o.mode=1<<b.g.o;break;case 42:d=b.D;d.g=15;d.style.set(4);X2(d);a3(b);break;case 43:a3(b);break;case 44:a=b.i;switch(b.style.get()){case 1:case 2:case 3:S2(a,d)}W2(a,0,15);break;case 45:b:{a=
b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.i=1;break b}case 3:}2>a.g&&(a.g=2,a.row<a.g&&(a.row=a.g));b=a.row-a.g+1;S2(a,d);V2(a,b,b+1,a.g-1);W2(a,a.row,1)}break;case 46:W2(b.l,0,15);break;case 47:S2(b.i,d),b.l.updateTime(b.o.i+0),d=b.l,b.l=b.i,b.i=d,$2(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.g,32<(d.i+=c&3)&&(d.i=32)}}},b3=function(a,b,c,d,e,f,k){var l=f[0],m=k[l.getAttribute("p")];
if(1==m.bd){var n=f[1],q=f[2],r=f[3];l.getAttribute("p");l.getAttribute("t");n.getAttribute("t");q.getAttribute("t");r.getAttribute("t");f=g.Rd("RUBY");l=l.textContent;var u=g.Rd("SPAN");u.innerText=l;f.appendChild(u);n.getAttribute("p");u=g.Rd("RP");l=n.textContent;u.innerText=l;f.appendChild(u);k=k[q.getAttribute("p")];l=q.textContent;q=g.Rd("RT");q.innerText=l;f.appendChild(q);l=k.bd;if(10==l||11==l||12==l||13==l||14==l)if(g.Ah(q,"text-emphasis","filled circle"),g.Ah(q,"webkit-text-emphasis","filled circle"),
k.bd==k.bd==11||13==k.bd)g.Ah(q,"webkit-text-emphasis-position","under left"),g.Ah(q,"text-emphasis-position","under left");if(4==k.bd||7==k.bd||12==k.bd||14==k.bd)g.Ah(f,"ruby-position","over"),g.Ah(f,"-webkit-ruby-position","before");else if(5==k.bd||6==k.bd||11==k.bd||13==k.bd)g.Ah(f,"ruby-position","under"),g.Ah(f,"-webkit-ruby-position","after");r.getAttribute("p");l=r.textContent;r=g.Rd("RP");r.innerText=l;f.appendChild(r);return new z2(a,b,e,c,f,d,m)}switch(m.bd){case 9:case 10:m.ye=1;break;
case 11:m.ye=2;break;case 12:m.ye=3;break;case 13:m.ye=4;break;case 14:m.ye=5}return new z2(a,b,e,c,l.textContent||"",d,m)},c3=function(){g.B.apply(this,arguments)},d3=function(a){c3.call(this);
this.l={};this.F={};this.H={};this.u="_"+B2++;this.A=a;this.D={};this.i=this.g=null;this.C=!0},e3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return parseFloat(c)},f3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},g3=function(a,b){var c=e3(a,b);
return void 0!=c?c:null},i3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return h3.test(c),c},j3=function(a,b){var c={},d=b.getAttribute("ws");
g.Sa(c,d?a.H[d]:a.A);d=g3(b,"mh");null!=d&&(c.Gq=d);d=g3(b,"ju");null!=d&&(c.textAlign=d);d=g3(b,"pd");null!=d&&(c.ze=d);d=g3(b,"sd");null!=d&&(c.vA=d);d=i3(b,"wfc");null!=d&&(c.windowColor=d);d=e3(b,"wfo");void 0!=d&&(c.windowOpacity=d/255);return c},k3=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Sa(c,a.F[d]);d=g3(b,"ap");null!=d&&(c.Uf=d);d=e3(b,"cc");null!=d&&(c.Ql=d);d=e3(b,"ah");null!=d&&(c.Se=d);d=e3(b,"rc");null!=d&&(c.Ik=d);d=e3(b,"av");null!=d&&(c.Gg=d);return c},l3=function(a,b,c,d){var e={};
g.Sa(e,k3(a,b));g.Sa(e,j3(a,b));d?g.ac(e,a.A)?(d=a.u,e=a.A):d="_"+B2++:d=b.getAttribute("id")||"_"+B2++;a=e3(b,"t")+c;b=e3(b,"d")||0x8000000000000;if(2==e.ze||3==e.ze)c=e.Ik,e.Ik=e.Ql,e.Ql=c;return new A2(a,b,0,d,e)},m3=function(a,b,c,d,e,f,k){E2.call(this,a,b,c,d,e,f,k);
this.type=1},n3=function(a,b,c){this.C=c;
this.version=this.A=this.o=this.g=0;this.i=new DataView(a);this.l=[]},o3=function(a){var b=a.g;
a.g+=1;return a.i.getUint8(b)},p3=function(a){var b=a.g;
a.g+=4;return a.i.getUint32(b)},q3=function(a,b){c3.call(this);
this.i=a;this.track="CC3"==b.l?4:0;this.g=new L2;this.g.l=1<<this.track},s3=function(a){if(g.Ea(a))return!1;
a=new n3(a,8,0);return r3(a)},r3=function(a){if(!(a.g<a.i.byteLength)||1380139777!=p3(a))return!1;
a.version=o3(a);if(1<a.version)return!1;o3(a);o3(a);o3(a);return!0},t3=function(a,b,c,d,e,f,k){E2.call(this,a,b,c,d,e,f,k);
g.I(this.element,"ytp-caption-window-rollup");this.type=2;this.F=[];this.I=this.H=this.fa=0;this.M=NaN;this.xa=0;this.Da=null;this.da=new g.K(this.BK,433,this);g.D(this,this.da)},Npa=function(a,b){return(a.u?b.offsetHeight:b.offsetWidth)+1},Opa=function(a){if(isNaN(a.M)){var b=a.l.Ql;
if(b){var c=g.Rd("SPAN");g.ae(c,"\u2013".repeat(b));g.Ah(c,F2(a,a.l.wb));a.A.appendChild(c);a.M=c.offsetWidth;a.A.removeChild(c)}else a.M=0}return a.M},Ppa=function(a,b){if(!b)return"";
a.u&&1!=a.o.params.vA&&(b*=-1);return"translate"+(a.u?"X":"Y")+"("+b+"px)"},u3=function(a){a.F=[].concat(g.ea(document.getElementsByClassName("caption-visual-line")));
for(var b=a.o.params.Ik,c=0,d=0,e=a.F.length-1;c<b&&-1<e;){var f=a.F[e];d+=a.u?f.offsetWidth:f.offsetHeight;c++;e--}a.F.length<b&&(d*=b/a.F.length);a.H=d;a.I=Math.max(Opa(a),a.xa,Npa(a,a.A))},Qpa=function(a,b){u3(a);
var c=a.F.reduce(function(e,f){return(a.u?f.offsetWidth:f.offsetHeight)+e},0);
c=a.H-c;if(c!=a.fa){var d=0<c&&0==a.fa;b||isNaN(c)||d||(g.I(a.element,"ytp-rollup-mode"),g.fo(a.da));g.Ah(a.A,"transform",Ppa(a,c));a.fa=c}u3(a)},v3=function(){c3.call(this)},w3=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Re=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3==q.nodeType){q=new z2(b,c,d,e.id,q.nodeValue,f||0<n,g.Xb(l)?void 0:l);m.push(q);var r=e;g.D(r,q);r.g.push(q)}else r={},g.Sa(r,l),w3(a,b,c,d,e,!0,q,r,m)}},x3=function(a){var b=0;
a=g.p(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+parseFloat(c.value);return 1E3*b},y3=function(a,b,c,d){d=Object.assign({Gq:0},d);
return new A2(a,b,c,"_"+B2++,d)},z3=function(a){g.B.call(this);
this.i=a;this.g=null},C3=function(a){g.IK.call(this,a);
this.l=g.W(a);this.o=a.getVideoData();this.wa=g.gK(a);this.O=a;var b=null,c=g.Vo("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.Fo(c));this.aa=b;this.u={wb:{}};this.A={wb:{}};this.H=[];this.M={};this.V={};this.P=!1;this.ma=g.YU(this.o,this.O);this.xa=!!this.o.captionTracks.length;this.Ba=!!this.o.kj;this.ka="3"==this.l.l;b=a.app.u;c=!(!b||!b.Vk());this.va=!(!b||!b.Bh());this.C=this.ka&&c&&!this.ma;this.I=!this.C&&this.ka&&this.va&&this.ma;this.i=this.D=this.F=this.R=this.da=null;this.Z=
new z3(this.l);g.D(this,this.Z);c=b=this.g=null;this.C||(b=new g.bo(this.KA,void 0,this),g.D(this,b),c=new g.K(this.YL,2E3,this),g.D(this,c));this.X=b;this.fa=c;this.ba=new g.zs(this);g.D(this,this.ba);this.C||this.ba.K(a,"resize",this.Ls);this.ba.K(a,"onPlaybackAudioChange",this.dI);this.ba.K(a,g.VD("captions"),this.RE,this);this.ba.K(a,"crx_captions",this.SE,this);A3(this,B3(this,"display-settings")||{})},D3=function(a){if(1==a.l.ag||1==a.o.ag||"alwayson"==g.DB(a.o,"yt:cc"))return!0;
if(2==a.l.ag){var b=B3(a,"module-enabled");if(null!=b)return!!b}if(a.o.captionTracks.length)var c=a.player.getAudioTrack().Wo;return"ON"==c||"on"==g.DB(a.o,"yt:cc")},E3=function(a,b){if(a.g&&(void 0===b||!b)||!a.o.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.dm||"FORCED_ON"==c.Wo},G3=function(a,b){if(a.i){if(a.D&&a.D.g)return a.D.g;
var c=b;c||(c=a.Ba?!1:a.xa?!1:!0);c=n2(a.i.i,c);for(var d=[a.o.Zf,a.l.Zf,g.DB(a.o,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(l2(c[f])==d[e])return c[f];return a.D&&a.D.mp?a.D.mp:(d=c.find(function(k){return k.isDefault}))?d:c[0]||F3(a)}return null},F3=function(a){return a.D&&a.D.dm},H3=function(a){var b=F3(a);
return!!b&&a.g==b},I3=function(a,b){for(var c=a.O.app.u.ga().textTracks,d=a.g.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},K3=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.P=c,a.P&&J3(a,"module-enabled",!!b));a.g=b;E3(a)&&(a.g=F3(a));a.load()},Rpa=function(a,b){var c=a.wa.getVideoContentRect(!0).height;
if(!c)return null;var d=a.wa.getPlayerSize();switch(null!=b.params.Gq?b.params.Gq:1<b.g.length?1:0){case 1:return new m3(b,a.u,a.A,c,d.width,d.height,a.l.experiments);case 2:return new t3(b,a.u,a.A,c,d.width,d.height,a.l.experiments);default:return new E2(b,a.u,a.A,c,d.width,d.height,a.l.experiments)}},A3=function(a,b,c){var d=L3.wb;
a.u={};g.Sa(a.u,L3);a.u.wb={};g.Sa(a.u.wb,d);a.A={wb:{}};var e=b.backgroundOverride?a.A:a.u,f=b.background||d.background;h3.test(f);e.wb.background=f;e=b.colorOverride?a.A:a.u;f=b.color||d.color;h3.test(f);e.wb.color=f;e=b.windowColorOverride?a.A:a.u;f=b.windowColor||L3.windowColor;h3.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.A:a.u;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.wb.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.A:a.u;f=b.fontSizeIncrement;null==f&&(f=d.fontSizeIncrement);
e.wb.fontSizeIncrement=f;f=b.fontStyleOverride?a.A:a.u;e=b.fontStyle;null==e&&(e=d.bold&&d.Re?3:d.bold?1:d.Re?2:0);f=f.wb;switch(e){case 1:f.bold=!0;delete f.Re;break;case 2:delete f.bold;f.Re=!0;break;case 3:f.bold=!0;f.Re=!0;break;default:delete f.bold,delete f.Re}e=b.textOpacityOverride?a.A:a.u;f=b.textOpacity;null==f&&(f=d.textOpacity);e.wb.textOpacity=f;e=b.windowOpacityOverride?a.A:a.u;f=b.windowOpacity;null==f&&(f=L3.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?a.A:a.u;f=b.charEdgeStyle;
null==f&&(f=d.charEdgeStyle);e.wb.charEdgeStyle=f;e=b.fontFamilyOverride?a.A:a.u;f=b.fontFamily;null==f&&(f=d.fontFamily);e.wb.fontFamily=f;a.loaded&&a.Ls();c&&J3(a,"display-settings",b)},N3=function(a,b){if(b&&!a.F){var c=C2({ze:0,
lang:"en"});a.F=[c,new z2(c.start,c.end-c.start,0,c.id,"Captions look like this")];g.nK(a.player,a.F)}else!b&&a.F&&(M3(a,a.F),a.F=null)},M3=function(a,b){g.pK(a.player,b);
(0,g.A)(b,function(c){g.cb(this.H,c)},a);
a.X.Lj()},B3=function(a,b){if(!a.aa)return null;
try{var c=a.aa.get(b)}catch(d){a.aa.remove(b)}return c},J3=function(a,b,c){if(a.aa)try{a.aa.set(b,c)}catch(d){}};
g.lC.prototype.mj=g.ca(13,function(){for(var a=g.Ed(document,"track",void 0,this.g),b=0;b<a.length;b++)g.Wd(a[b])});
g.OW.prototype.mj=g.ca(12,function(){this.g.mj()});
g.lC.prototype.Vk=g.ca(11,function(){return!!this.g.textTracks});
g.OW.prototype.Vk=g.ca(10,function(){return this.g.Vk()});
g.lC.prototype.fj=g.ca(9,function(a){for(var b=0;b<a.length;b++)this.g.appendChild(a[b])});
g.OW.prototype.fj=g.ca(8,function(a){this.g.fj(a)});
g.cC.prototype.Bh=g.ca(7,function(){});
g.lC.prototype.Bh=g.ca(6,function(){return!(!this.g.textTracks||!this.g.textTracks.addEventListener)});
g.OW.prototype.Bh=g.ca(5,function(){return this.g.Bh()});
g.yz.prototype.Lq=g.ca(3,function(a){return a?this.toString()==a.toString():!1});
g.wt.prototype.qm=g.ca(2,function(a){return(a=this.kg(a))?a.i:0});
g.rw.prototype.qm=g.ca(1,function(){return 0});
var Spa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,Bpa=/#(.)(.)(.)/,Apa=/^#(?:[0-9a-f]{3}){1,2}$/i,h3=/^#(?:[0-9a-f]{3}){1,2}$/i;g.t(p2,g.B);p2.prototype.nz=function(){return!1};
p2.prototype.T=function(){this.Hg();g.B.prototype.T.call(this)};
g.t(q2,p2);q2.prototype.Dq=function(a,b,c){b=this.Hj(a,b);var d=(0,g.x)(function(e){this.g=null;c(e.responseText,a)},this);
this.Hg();this.g=g.Iq(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
q2.prototype.Eq=function(a){if(this.l)for(var b=g.p(this.l.captionTracks),c=b.next();!c.done;c=b.next())o2(this.i,c.value);a()};
q2.prototype.Hj=function(a,b){var c=a.F,d={fmt:b};a.g&&(d.tlang=l2(a));return g.rq(c,d)};
q2.prototype.Hg=function(){this.g&&this.g.abort()};
r2.prototype.contains=function(a){a=g.ob(this.Ta,a);return 0<=a||0>a&&1==(-a-1)%2};
r2.prototype.length=function(){return this.Ta.length/2};
g.t(s2,g.B);g.h=s2.prototype;g.h.T=function(){g.B.prototype.T.call(this);this.i&&this.i.cancel()};
g.h.qx=function(a){var b=this;if(this.D.di())var c=this.u.K(this.l,"progresssync",function(){b.D.index.Eb()&&(b.reset(),b.g=null,t2(b,b.l.getCurrentTime()),b.u.La(c))});
else t2(this,a)};
g.h.OF=function(){t2(this,this.l.getCurrentTime())};
g.h.reset=function(){this.A=new r2;this.i&&(this.i.cancel(),this.i=null)};
g.h.Iw=function(){var a;if(a=null!==this.g)a=this.g,a=a.g.Hf(a);!a||this.i||this.g&&30<this.g.startTime-this.l.getCurrentTime()||(a=this.g,a=a.g.ni(a),a.g[0].duration&&(this.A.contains(a.g[0].i)||u2(this,a),this.g=g.Va(a.g)));this.H.start()};
g.h.wK=function(a){var b=!(this.C?a.response:a.responseText)||400<=a.status,c=g.zw(a);c?(a=g.Hv(this.o,this.I,{}),b=this.o,g.Cv(b.i,a,c),b.requestId=a.get("req_id"),u2(this,this.o)):(b||null===this.F||(c=this.o.g[0],this.C?this.F(a.response,1E3*(c.startTime+this.l.Ib())):this.F(a.responseText,1E3*(c.startTime+this.l.Ib()))),this.i=this.o=null)};
g.t(v2,p2);g.h=v2.prototype;g.h.Dq=function(a,b,c){this.Hg();b=Dpa(this,a.getId());b||(b=a.i,b=this.g.i?x2(this,b,"386"):x2(this,b));if(b){var d=1E3*(b.index.qm(b.index.ne())-b.index.Gc(b.index.ne()));this.l=new s2(new g.Xu,this.C,b,function(e,f){c(e,a,f,d)},this.A||g.Ru(b.info),(0,g.x)(function(){this.l&&this.l.reset();
this.o=!0},this))}};
g.h.nz=function(){var a=this.o;this.o=!1;return a};
g.h.Eq=function(a){var b;this.A?b=[new g.yz({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.yz({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.g.i?w2(this,"386"):w2(this);b=g.p(b);for(var c=b.next();!c.done;c=b.next())o2(this.i,c.value);a()};
g.h.Hg=function(){this.l&&(this.l.dispose(),this.l=null)};
g.h.Hj=function(){return""};
g.t(y2,p2);y2.prototype.Dq=function(a,b,c){b=this.Hj(a,b);var d=(0,g.x)(function(e){this.g=null;c(e.responseText,a)},this);
this.Hg();this.g=g.Iq(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
y2.prototype.Eq=function(a){var b=this.o,c={type:"list",tlangs:1,v:this.l,vssids:1};this.A&&(c.asrs=1);b=g.rq(b,c);c=(0,g.x)(function(d){this.g=null;if((d=d.responseXML)&&d.firstChild){for(var e=g.p(d.getElementsByTagName("track")),f=e.next();!f.done;f=e.next()){var k=f.value;f=k.getAttribute("lang_code");var l=k.getAttribute("lang_translated"),m=k.getAttribute("name"),n=k.getAttribute("kind"),q=k.getAttribute("id"),r="true"==k.getAttribute("lang_default"),u="true"==k.getAttribute("cantran");k=k.getAttribute("vss_id");
o2(this.i,new g.yz({languageCode:f,languageName:l,name:m,kind:n,id:q,is_servable:!0,is_translateable:u,vss_id:k,is_default:r}))}d=d.getElementsByTagName("target");e=d.length;for(f=0;f<e;f++)l=d[f].getAttribute("lang_code"),m=d[f].getAttribute("lang_translated"),n=d[f].getAttribute("lang_original"),q=d[f].getAttribute("id"),r="true"==d[f].getAttribute("lang_default"),l={languageCode:l,languageName:m,languageOriginal:n,id:q,isDefault:r},this.C[l.languageCode]=l.languageName,this.u.push(l)}a()},this);
this.Hg();this.g=g.Iq(b,{format:"RAW",onSuccess:c,withCredentials:!0})};
y2.prototype.Hj=function(a,b){var c=this.o,d={v:this.l,type:"track",lang:a.i,name:a.getName(),kind:a.o,fmt:b};a.g&&(d.tlang=l2(a));return c=g.rq(c,d)};
y2.prototype.Hg=function(){this.g&&this.g.abort()};var Epa=["left","right","center","justify"];var L3={windowColor:"#080808",windowOpacity:0,textAlign:2,Uf:7,Se:50,Gg:100,wb:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.t(z2,g.SD);z2.prototype.toString=function(){return g.SD.prototype.toString.call(this)};g.t(A2,g.SD);A2.prototype.toString=function(){return g.SD.prototype.toString.call(this)};
var B2=0;g.t(E2,g.V);g.h=E2.prototype;g.h.NF=function(a,b){var c=g.Qh(this.element,this.element.parentElement);this.ma=a-c.x;this.va=b-c.y;g.I(this.element,"ytp-dragging")};
g.h.MF=function(a,b){var c=g.Th(this.element),d=a-this.ma-.02*this.Pa,e=b-this.va-.02*this.Ma,f=(d+c.width/2)/this.X*3;f=Math.floor(g.pd(f,0,2));var k=(e+c.height/2)/this.wa*3;k=Math.floor(g.pd(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.X;d=100*g.pd(d,0,1);c=(e+k/2*c.height)/this.wa;c=100*g.pd(c,0,1);this.o.params.Uf=l;this.o.params.Gg=c;this.o.params.Se=d;this.l.Uf=l;this.l.Gg=c;this.l.Se=d;this.Mz()};
g.h.LF=function(){g.Wn(this.element,"ytp-dragging")};
g.h.Mz=function(){this.zh(this.C)};
g.h.zh=function(a){var b=Math.min(this.Av(),this.X),c=this.zv(),d="";3==this.o.params.ze&&(d="rotate(180deg)");g.Ah(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Ko(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.l.Se+2;d=this.l.Uf;switch(d){case 0:case 3:case 6:a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.A.offsetWidth;
b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.l.Gg+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.Ah(this.element,a)};
g.h.Ko=function(a){var b;for(b=0;b<a.length&&a[b]==this.C[b];b++);if(this.O||this.C.length>b)b=0,this.O=!1,this.C=[],this.D=this.V=this.R=null,g.Ud(this.A);for(;b<a.length;b++)I2(this,a[b])};
g.h.Av=function(){return 0};
g.h.zv=function(){return 0};
g.h.toString=function(){return g.V.prototype.toString.call(this)};J2.prototype.u=function(){};L2.prototype.clear=function(){this.o=this.i=this.mode=0;this.g=[];this.reset()};
L2.prototype.reset=function(){this.mode=0;this.u.reset(0);this.A.reset(1)};
var M2=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];O2.prototype.set=function(a){this.g=a};
O2.prototype.get=function(){return this.g};
P2.prototype.clear=function(){this.g=0};
P2.prototype.update=function(){this.g=2==this.g?1:0};
P2.prototype.matches=function(a,b){return 0!=this.g&&a==this.l&&b==this.i};
Q2.prototype.fg=function(a){this.Qd=a.Qd;this.timestamp=a.timestamp};
Q2.prototype.reset=function(){this.timestamp=this.Qd=0};
R2.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.l[b][c].timestamp=a};
R2.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.l[b][c];a=0==d.Qd?a+"_":a+String.fromCharCode(d.Qd)}a+="\n"}return a};
R2.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.l[b][c].reset();this.o=a;this.g=0;this.i=this.row=1};
var Ipa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Jpa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Kpa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Lpa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];Y2.prototype.reset=function(a,b){this.u=b;this.style.set(2);this.i=this.A;this.l=this.C;this.g=this.i;var c=(a<<2)+(b<<1);this.A.reset(c);this.C.reset(c);this.D.reset((a<<2)+(b<<1)+1)};
K2.prototype.reset=function(a){this.u=a;this.g.clear();this.o=this.l;this.l.reset(a,0);this.A.reset(a,1)};g.t(c3,g.B);c3.prototype.reset=function(){};g.t(d3,c3);d3.prototype.reset=function(){this.D={};this.i=this.g=null;this.C=!0};
d3.prototype.o=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.p(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.p(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.l,l={},m=c.getAttribute("p");m&&g.Sa(l,this.l[m]);m=f3(c,"b");null!=m&&(l.bold=
m);m=f3(c,"i");null!=m&&(l.Re=m);m=f3(c,"u");null!=m&&(l.underline=m);m=g3(c,"et");null!=m&&(l.charEdgeStyle=m);m=g3(c,"of");null!=m&&(l.offset=m);m=i3(c,"bc");null!=m&&(l.background=m);m=i3(c,"ec");null!=m&&(l.yu=m);m=i3(c,"fc");null!=m&&(l.color=m);m=g3(c,"fs");null!=m&&0!=m&&(l.fontFamily=m);m=e3(c,"sz");void 0!=m&&(l.fontSizeIncrement=m/100-1);m=e3(c,"bo");void 0!=m&&(l.backgroundOpacity=m/255);m=e3(c,"fo");void 0!=m&&(l.textOpacity=m/255);m=g3(c,"rb");null!=m&&10!=m&&(l.bd=10<m?m-1:m);m=g3(c,
"hg");null!=m&&(l.OD=m);c=g3(c,"te");null!=c&&(2==c&&(l.bold=!1,c=1),l.ye=c);k[d]=l;break;case "ws":d=c.getAttribute("id");this.H[d]=j3(this,c);break;case "wp":d=c.getAttribute("id"),this.F[d]=k3(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.p(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.g=l3(this,d,e,!1);g.D(this,this.g);(d=this.D[this.g.id])&&d.end>this.g.start&&(d.end=this.g.start);this.D[this.g.id]=this.g;c.push(this.g);break;case "p":var n=
e;k=[];l=d.getAttribute("w")||this.u;m=!!f3(d,"a");n=(e3(d,"t")||0)+n;var q=e3(d,"d")||5E3;m||(!this.C&&this.i&&this.i.windowId==l&&this.i.end>n&&(this.i.end=n),this.i&&"\n"==this.i.text&&(this.i.text=""));var r=m?6:5,u=this.l[d.getAttribute("p")],z=[].concat(g.ea(d.childNodes));z.length&&(this.C=null!=d.getAttribute("d"));for(var C=0;C<z.length;C++){var E=z[C];0<C&&(m=!0);var F=void 0;1==E.nodeType&&(F=E);if(F&&"s"==F.tagName)if((E=this.l[F.getAttribute("p")])&&E.bd)1==E.bd?(F=b3(n,q,l,m,r,z.slice(C,
C+4),this.l),C+=3):F=b3(n,q,l,m,r,[F],this.l);else{var L=F;F=n;E=q;var Z=l,qa=m,ya=r,gb=L.textContent?L.textContent:"",se=this.l[L.getAttribute("p")];L=e3(L,"t")||0;F=new z2(F+L,E-L,ya,Z,gb,qa,se)}else F=new z2(n,q,r,l,E.textContent||"",m,u);k.push(F);this.i=F}if(0<k.length)for(k[0].windowId==this.u&&(this.g=l3(this,d,e,!0),g.D(this,this.g),c.push(this.g)),d=g.p(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.g.id,l=this.g,g.D(l,k),l.g.push(k),c.push(k)}e=c}else e=[];return e};g.t(m3,E2);m3.prototype.Ko=function(a){var b=this.o.g;E2.prototype.Ko.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.g==e)var d=f;else{d={};g.Sa(d,c.g);g.Sa(d,Tpa);var e=c.g;var f=d}I2(this,c,d)}};
var Tpa={MD:!0};g.t(n3,J2);n3.prototype.u=function(a,b,c,d,e){if(c<d){var f="_"+B2++;c=c/1E3-this.C;d=d/1E3-this.C;a=new A2(c,d-c,5,f,{textAlign:0,Uf:0,Se:2.5*b,Gg:5.33*a});e=new z2(c,d-c,5,f,e);this.l.push(a);this.l.push(e)}};
g.t(q3,c3);q3.prototype.o=function(a){a=new n3(a,a.byteLength,this.i);if(r3(a)){for(;a.g<a.i.byteLength;)for(0==a.version?a.o=p3(a)*(1E3/45):1==a.version&&(a.o=4294967296*p3(a)+p3(a)),a.A=o3(a);0<a.A;a.A--){var b=o3(a),c=o3(a),d=o3(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.g,b.g.push({time:a.o,type:this.track,ru:c,tu:d,order:b.g.length}))}Hpa(this.g,a);return a.l}return[]};
q3.prototype.reset=function(){this.g.clear()};g.t(t3,E2);g.h=t3.prototype;g.h.Mz=function(){g.go(this.da)};
g.h.BK=function(){g.Wn(this.element,"ytp-rollup-mode");this.zh(this.Da,!0)};
g.h.zv=function(){return this.u?this.I:this.H};
g.h.Av=function(){return this.u?this.H:this.I};
g.h.zh=function(a,b){this.Da=a;if(this.o.params.Ik){for(var c=0,d=0;d<this.C.length&&c<a.length;d++)this.C[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.C.concat(a.slice(c)));this.xa=this.I;this.H=this.I=0;E2.prototype.zh.call(this,a);Qpa(this,b);E2.prototype.zh.call(this,a)}else E2.prototype.zh.call(this,a)};g.t(v3,c3);
v3.prototype.o=function(a,b){for(var c=[],d=a.split(Upa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!Vpa.test(f)){var l=O3.exec(f);if(l&&4<=l.length){var m=x3(l[1]),n=x3(l[2])-m;m+=k;var q,r=q=void 0,u=void 0,z=void 0,C=l[3];l={textAlign:2};C=g.p(C?C.split(" "):[]);for(var E=C.next();!E.done;E=C.next())if(E=E.value.split(":"),2==E.length){var F=E[1];switch(E[0]){case "line":E=F.split(",");E[0].endsWith("%")&&(z=E[0],l.Gg=Number.parseInt(z,10),2==E.length&&(u=E[1].trim()));break;case "position":E=F.split(",");
r=E[0];l.Se=Number.parseInt(r,10);2==E.length&&(q=E[1].trim());break;case "align":switch(F){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}z||(l.Gg=100,u||(u="end"));if(!r)switch(l.textAlign){case 0:l.Se=0;break;case 1:l.Se=100;break;default:l.Se=50}r=0;switch(u){case "center":r+=3;break;case "end":r+=6;break;default:r+=0}switch(q){case "line-left":r+=0;break;case "center":r+=1;break;case "line-right":r+=2;break;default:switch(l.textAlign){case 0:r+=
0;break;case 2:r+=1;break;case 1:r+=2}}l.Uf=0>r||8<r?7:r;q=l;f=f.substring(O3.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");r=q;q=f;f={};if(0>q.indexOf("<")&&0>q.indexOf("&"))k=y3(m,n,5,r),n=new z2(m,n,5,k.id,q,!1,g.Xb(f)?void 0:f),c.push(k),c.push(n),g.D(k,n),k.g.push(n);else for(u=q.split(Wpa),1==u.length?(q=5,r=y3(m,n,q,r)):(z=q=6,r=Object.assign({Ql:32},r),r=new A2(m,n,z,"_"+B2++,r)),c.push(r),z=m,l=0;l<u.length;l++)C=u[l],0==l%2?(E=g.Yn("<html>"+C+"</html>"),E.getElementsByTagName("parsererror").length?
(F=E.createElement("span"),F.appendChild(E.createTextNode(C))):F=E.firstChild,w3(this,z,n-(z-m),q,r,0<l,F,f,c)):z=x3(C)+k}O3.lastIndex=0}}return c};
var Vpa=/^NOTE/,Upa=/(?:\r\n|\r|\n){2,}/,O3=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Wpa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.t(z3,g.B);z3.prototype.clear=function(){this.g&&this.g.dispose();this.g=null};
z3.prototype.reset=function(){this.g&&this.g.reset()};
z3.prototype.T=function(){this.clear();g.B.prototype.T.call(this)};g.t(C3,g.IK);g.h=C3.prototype;g.h.T=function(){if(this.C||this.I){var a=this.O.app.u;a&&a.mj()}else N3(this,!1);g.IK.prototype.T.call(this)};
g.h.Nk=function(){return this.ka?this.C||this.I:E3(this)?!0:D3(this)};
g.h.load=function(){g.IK.prototype.load.call(this);var a=!g.P(this.l.experiments,"web_player_captions_track_list_changed_killswitch");this.D=this.player.getAudioTrack();if(this.i)this.g&&(this.Z.clear(),this.C?I3(this,!0):3!=this.player.getPresentingPlayerType()&&this.i.Dq(this.g,"srv3",(0,g.x)(this.iL,this)),!a||this.C||this.I||H3(this)||this.player.la("captionschanged",k2(this.g))),a||(this.g&&!H3(this)?this.player.la("captionschanged",k2(this.g)):this.player.la("onCaptionsTrackListChanged"));else{var b;
this.ma?b=new v2(this.o.ha,this.player):this.xa?b=new q2(this.l,this.o,this.player.getAudioTrack()):b=new y2(this.o.kj,this.o.videoId,this.o.Zf||this.l.Zf||g.DB(this.o,"yt:cc_default_lang")||this.l.Wb,this.o.Uo,this.l);this.i=b;g.D(this,this.i);b.Eq((0,g.x)(this.hL,this))}};
g.h.unload=function(){this.C&&this.g?I3(this,!1):(this.fa&&g.ho(this.fa),g.qK(this.player,"captions"),this.H=[],this.i&&this.i.Hg(),this.Z.clear(),this.F&&g.nK(this.player,this.F),this.Ls());g.IK.prototype.unload.call(this);var a=g.U(this.player.app);a&&g.VH(a.A);this.player.la("captionschanged",{})};
g.h.hL=function(){var a;this.P||D3(this)?a=G3(this,this.P):E3(this)&&(a=F3(this));if(this.C||this.I){for(var b=n2(this.i.i,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.zz(e),srclang:l2(e),id:e.toString()};this.I||(f.src=this.i.Hj(e,"vtt"));e==a&&(f["default"]=1);c.push(g.Qd("TRACK",f))}a=this.O.app.u;a.fj(c);c=a.ga();this.va&&this.ba.K(c.textTracks,"change",this.jL)}else!this.g&&a&&K3(this,a),this.player.la("onCaptionsTrackListChanged"),this.player.la("onApiChange")};
g.h.jL=function(){for(var a=this.O.app.u.ga().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=a[c].id;var d=n2(this.i.i,!0);for(var e=0;e<d.length;e++)if(d[e].toString()==b){b=d[e];break a}b=null}(this.loaded?this.g:null)!=b&&K3(this,b,!0)};
g.h.GM=function(){!this.g&&this.C||this.unload()};
g.h.iL=function(a,b,c,d){if(a){this.i.nz()&&(this.H=[],g.qK(this.O,"captions"),this.X.Lj(),this.Z.reset());var e=this.Z;c=c||0;d=d||0;if(!g.Ea(a)){var f=new DataView(a);if(8<=f.byteLength&&1718909296==f.getUint32(4)&&(f=g.Qt(f,0,1835295092),a=a.slice(f.dataOffset,f.dataOffset+f.size),!s3(a))){a=new Uint8Array(a);f=[];for(var k=0,l=0;k<a.length;){var m=a[k++];if(128>m)f[l++]=String.fromCharCode(m);else if(191<m&&224>m){var n=a[k++];f[l++]=String.fromCharCode((m&31)<<6|n&63)}else if(239<m&&365>m){n=
a[k++];var q=a[k++],r=a[k++];m=((m&7)<<18|(n&63)<<12|(q&63)<<6|r&63)-65536;f[l++]=String.fromCharCode(55296+(m>>10));f[l++]=String.fromCharCode(56320+(m&1023))}else n=a[k++],q=a[k++],f[l++]=String.fromCharCode((m&15)<<12|(n&63)<<6|q&63)}a=f.join("")}}if(a)try{if(g.Ea(a)){if("WEBVTT"==a.substring(0,6)){b=a;var u=c;e.g||(e.g=new v3);var z=e.g.o(b,u);.01>Math.random()&&g.Gp(Error("Deprecated subtitles format in web player: WebVTT"));var C=z}else b:{z=a;u=g.Yn(z);if(!u||!u.firstChild){var E=Error("Invalid caption track data");
E.params=z;throw E;}if("timedtext"==u.firstChild.tagName){if(3==parseInt(u.firstChild.getAttribute("format"),10)){if(!e.g){z={};var F=l2(b);F&&(z.lang=F,Spa.test(F)&&(z.ze=1));e.g=new d3(z,e.i)}C=e.g.o(u,c);break b}var L=Error("Unsupported subtitles format in web player (Format2)");L.params=z;throw L;}if("transcript"==u.firstChild.tagName){var Z=Error("Unsupported subtitles format in web player (Format1)");Z.params=z;throw Z;}var qa=Error("Invalid caption track data");qa.params=z;throw qa;}var ya=
C}else{C=a;u=c;F=d;if(!s3(C))throw Error("Invalid binary caption track data");e.g||(e.g=new q3(F,b));ya=e.g.o(C,u)}var gb=ya}catch(se){g.M(se),e.clear(),gb=[]}else gb=[];g.nK(this.player,gb);!this.P||this.I||H3(this)||g.Ry(this.l)||g.Sy(this.l)||(g.ho(this.fa),gb=C2({Uf:0,Se:5,Gg:5,Ik:2,textAlign:0,ze:0,lang:"en"}),this.R=[gb],e=["Click "," for settings"],this.da||(ya=new g.QC(g.OP()),g.D(this,ya),this.da=ya.element),ya=gb.end-gb.start,(b=g.zz(this.g))&&this.R.push(new z2(gb.start,ya,0,gb.id,b)),
this.R.push(new z2(gb.start,ya,0,gb.id,e[0]),new z2(gb.start,ya,0,gb.id,this.da,!0),new z2(gb.start,ya,0,gb.id,e[1],!0)),g.nK(this.player,this.R),g.fo(this.fa));!this.P||this.I||H3(this)||(J3(this,"module-enabled",!0),this.D&&(this.D.g=this.g),(gb=g.U(this.player.app))&&g.VH(gb.A));this.P=!1}};
g.h.RE=function(a){this.H.push(a);this.X.Lj()};
g.h.SE=function(a){g.cb(this.H,a);this.i instanceof v2&&this.i.A&&g.pK(this.player,[a]);this.X.Lj()};
g.h.SL=function(a){if(a instanceof A2){var b=this.M[a.id];b&&b.o!=a&&(b.dispose(),delete this.M[a.id],b=null);b||(b=Rpa(this,a))&&(this.M[a.id]=b)}else b=a.windowId,this.V[b]||(this.V[b]=[]),this.V[b].push(a)};
g.h.YL=function(){M3(this,this.R);this.R=null};
g.h.KA=function(){this.X.stop();g.Yb(this.V);this.H.sort(g.UD);var a=this.H;if(this.F){var b=(0,g.Xd)(a,function(c){return-1==this.F.indexOf(c)},this);
b.length&&(a=b)}(0,g.A)(a,this.SL,this);g.Kb(this.M,function(c,d){this.V[d]?(c.element.parentNode||g.uK(this.player,c.element,4),c.zh(this.V[d])):(c.dispose(),delete this.M[d])},this)};
g.h.cM=function(){A3(this,{},!0);g.P(this.l.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.la("captionssettingschanged")};
g.h.dD=function(){var a=L3.wb;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Re?3:a.bold?1:a.Re?2:0,textOpacity:a.textOpacity,windowColor:L3.windowColor,windowOpacity:L3.windowOpacity};var b=B3(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.h.PA=function(a,b){var c={};g.Sa(c,B3(this,"display-settings"));g.Sa(c,a);A3(this,c,b);this.player.la("captionssettingschanged")};
g.h.Ls=function(){!this.C&&this.loaded&&(g.Kb(this.M,function(a,b){a.dispose();delete this.M[b]},this),this.KA())};
g.h.uc=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.pd(b,-2,4);this.PA({fontSizeIncrement:c});return c;case "reload":b&&!this.C&&K3(this,this.g,!0);break;case "stickyLoading":void 0!=b&&this.l.rb&&J3(this,"module-enabled",!!b);break;case "track":if(!this.i)return{};if(b){if(this.C)break;if(!g.Oa(b))break;if(g.Xb(b)){K3(this,null,!0);break}for(var d=n2(this.i.i,!0),e=0;e<d.length;e++){var f=d[e];f.i!=b.languageCode||c&&f.l!=b.languageName||(c=b.translationLanguage?zpa(f,b.translationLanguage):
f)}!c||c==this.g&&this.loaded||K3(this,c,!0)}else return this.loaded&&this.g&&!H3(this)?k2(this.g):{};return"";case "tracklist":return this.i?(0,g.ge)(n2(this.i.i,!(!b||!b.includeAsr)),function(k){return k2(k)}):[];
case "translationLanguages":return this.i?this.i.u:[];case "sampleSubtitles":this.C||void 0==b||N3(this,!!b)}};
g.h.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.l.rb&&a.push("stickyLoading");return a};
g.h.Jj=function(){var a=this.g;return a?{cc:a.A}:{}};
g.h.AM=function(){this.loaded&&this.g&&!H3(this)?(J3(this,"module-enabled",!1),this.unload(),E3(this,!0)&&K3(this,F3(this),!1)):K3(this,H3(this)||!this.g?G3(this,!0):this.g,!0)};
g.h.dI=function(){var a=H3(this);E3(this,a)?K3(this,this.player.getAudioTrack().dm,!1):this.o.captionTracks.length&&(this.loaded&&this.unload(),this.Nk()&&(a?K3(this,G3(this),!1):this.load()))};g.dV.captions=C3;})(_yt_player);
