(function(g){var window=this;var P3=function(a,b,c){var d=b.oa();g.J(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.wc(c?c:"mqdefault.jpg");var f=b instanceof g.aB&&b.lengthSeconds?g.LQ(b.lengthSeconds):null,k=!!e;e=k&&"RD"==(new g.WD(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.aB?b.sa:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.gj||g.rN("Watch $TITLE",{TITLE:b.title}),duration:f,url:b.Kj(),is_live:l,is_list:k,
is_mix:e,background:c?"background-image: url("+c+")":""};b instanceof g.YD&&(d.playlist_length=b.getLength());a.update(d)},Q3=function(a,b){g.VC.call(this,{B:"div",
W:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.player=a;this.created=!1},R3=function(a){g.V.call(this,{B:"div",
W:["ytp-upnext","ytp-player-content"],L:{"aria-label":"{{aria_label}}"},J:[{B:"div",G:"ytp-cued-thumbnail-overlay-image",L:{style:"{{background}}"}},{B:"span",G:"ytp-upnext-top",J:[{B:"span",G:"ytp-upnext-header",U:"Up Next"},{B:"span",G:"ytp-upnext-title",U:"{{title}}"},{B:"span",G:"ytp-upnext-author",U:"{{author}}"}]},{B:"a",G:"ytp-upnext-autoplay-icon",L:{role:"button",href:"{{url}}","aria-label":"Play next video"},J:[{B:"svg",L:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},J:[{B:"circle",
G:"ytp-svg-autoplay-circle",L:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{B:"circle",G:"ytp-svg-autoplay-ring",L:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{B:"path",G:"ytp-svg-fill",L:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{B:"span",G:"ytp-upnext-bottom",J:[{B:"span",G:"ytp-upnext-cancel"},{B:"span",G:"ytp-upnext-paused",U:"Autoplay is paused"}]}]});
this.A=null;var b=this.i["ytp-upnext-cancel"];this.A=new g.V({B:"button",W:["ytp-upnext-cancel-button","ytp-button"],L:{tabindex:"0","aria-label":"Cancel autoplay"},U:"Cancel"});g.D(this,this.A);this.A.ca("click",this.iI,this);this.A.g(b);this.l=a;this.I=this.i["ytp-svg-autoplay-ring"];this.D=this.C=this.o=this.u=null;this.F=new g.K(this.Pl,5E3,this);g.D(this,this.F);this.H=0;this.K(this.i["ytp-upnext-autoplay-icon"],"click",this.VJ);this.oy();this.K(a,"autonavvisibility",this.oy);this.K(a,"mdxnowautoplaying",
this.nJ);this.K(a,"mdxautoplaycanceled",this.oJ);this.K(a,"mdxautoplayupnext",this.OA);3==this.l.getPresentingPlayerType()&&(a=(a=g.hK(g.bK(this.l)))?a.bD():null)&&this.OA(a)},S3=function(a,b){if(!a.o){g.Vp("a11y-announce","Up Next "+a.u.title);
a.H=g.N();a.o=new g.K((0,g.x)(a.Jo,a,b),25);a.Jo(b);var c=b||g.Q(g.W(a.l).experiments,"autoplay_time")||1E4;a.l.la("onAutonavCoundownStarted",c)}g.Wn(a.element,"ytp-upnext-autoplay-paused")},U3=function(a){T3(a);
a.H=g.N();a.Jo();g.I(a.element,"ytp-upnext-autoplay-paused")},T3=function(a){a.o&&(a.o.dispose(),a.o=null)},V3=function(a,b){b=void 0===b?!1:b;
if(g.P(g.W(a.l).experiments,"autonav_notifications")&&b&&window.Notification&&document.hasFocus){var c=Notification.permission;"default"==c?Notification.requestPermission():"granted"!=c||document.hasFocus()||(c=a.u.oa(),a.Pl(),a.C=new Notification("Up Next",{body:c.title,icon:c.wc()}),a.D=a.K(a.C,"click",a.NJ),a.F.start())}T3(a);a.l.nextVideo(!1,b)},W3=function(a){Q3.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.l=new g.V({B:"div",G:"ytp-subscribe-card",J:[{B:"img",G:"ytp-author-image",L:{src:b.Nd}},{B:"div",G:"ytp-subscribe-card-right",J:[{B:"div",G:"ytp-author-name",U:b.author},{B:"div",G:"html5-subscribe-button-container"}]}]});g.D(this,this.l);this.l.g(this.element);this.o=new g.WV("Subscribe",null,"Unsubscribe",null,!0,!1,b.Qf,b.subscribed,"trailer-endscreen",null,null,a);g.D(this,this.o);this.o.g(this.l.i["html5-subscribe-button-container"]);this.hide()},X3=function(a){var b=
g.W(a),c=g.Uw||g.Dh?{style:"will-change: opacity"}:void 0,d=b.i,e=["ytp-videowall-still"];
b.g&&e.push("ytp-videowall-show-text");g.V.call(this,{B:"a",W:e,L:{href:"{{url}}",target:d?b.A:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},J:[{B:"div",G:"ytp-videowall-still-image",L:{style:"{{background}}"}},{B:"span",G:"ytp-videowall-still-info",J:[{B:"span",G:"ytp-videowall-still-info-bg",J:[{B:"span",G:"ytp-videowall-still-info-content",L:c,J:[{B:"span",G:"ytp-videowall-still-info-title",U:"{{title}}"},{B:"span",G:"ytp-videowall-still-info-author",
U:"{{author_and_views}}"},{B:"span",G:"ytp-videowall-still-info-live",U:"Live"},{B:"span",G:"ytp-videowall-still-info-duration",U:"{{duration}}"}]}]}]},{B:"span",W:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],J:[{B:"span",G:"ytp-videowall-still-listlabel-icon"},"Playlist",{B:"span",G:"ytp-videowall-still-listlabel-length",J:[" (",{B:"span",U:"{{playlist_length}}"},")"]}]},{B:"span",W:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],J:[{B:"span",G:"ytp-videowall-still-listlabel-mix-icon"},
"Mix",{B:"span",G:"ytp-videowall-still-listlabel-length",U:" (50+)"}]}]});this.A=d;this.l=a;this.o=null;this.u=new g.zs(this);g.D(this,this.u);this.ca("click",this.D);this.ca("keypress",this.F);this.u.K(a,"videodatachange",this.C);g.W(a).F&&g.fO(a.app.R,this.element,this);this.C()},Y3=function(a){g.xK(a.l,a.element);
var b=a.o.oa().videoId,c=a.o.getPlaylistId();g.bY(a.l.app,b,a.o.Rb,c,void 0,void 0)},Z3=function(a){Q3.call(this,a,"videowall-endscreen");
this.H=a;this.C=0;this.o=[];this.D=this.u=this.A=null;this.F=this.R=!1;this.O=null;this.ba=new g.zs(this);g.D(this,this.ba);this.I=new g.K(g.Ra(g.I,this.element,"ytp-show-tiles"),0);g.D(this,this.I);var b=new g.V({B:"button",W:["ytp-button","ytp-endscreen-previous"],L:{"aria-label":"Previous"},J:[g.uP()]});g.D(this,b);b.g(this.element);b.ca("click",this.zF,this);this.M=new g.QC({B:"div",G:"ytp-endscreen-content"});g.D(this,this.M);this.M.g(this.element);b=new g.V({B:"button",W:["ytp-button","ytp-endscreen-next"],
L:{"aria-label":"Next"},J:[g.vP()]});g.D(this,b);b.g(this.element);b.ca("click",this.yF,this);this.l=new R3(a);g.D(this,this.l);g.uK(this.player,this.l.element,4);this.hide()},$3=function(a){return g.vK(a.player)&&a.iu()&&!a.D},a4=function(a,b){return(0,g.ge)(b.suggestions,function(c){c=g.$R(g.W(a.H),c);
g.D(a,c);return c})},b4=function(a){var b=a.Ne();
b!=a.R&&(a.R=b,a.player.N("autonavvisibility"))},d4=function(a){g.IK.call(this,a);
this.g=null;this.i=new g.zs(this);g.D(this,this.i);this.l=g.W(a);c4(a)?this.g=new Z3(this.player):this.l.Da?this.g=new W3(this.player):this.g=new Q3(this.player);g.D(this,this.g);g.uK(this.player,this.g.element,4);this.Lz();this.i.K(a,"videodatachange",this.Lz,this);this.i.K(a,g.VD("endscreen"),this.LE,this);this.i.K(a,"crx_endscreen",this.ME,this)},c4=function(a){a=g.W(a);
return a.Ba&&!a.Da};
g.t(Q3,g.VC);Q3.prototype.create=function(){this.created=!0};
Q3.prototype.destroy=function(){this.created=!1};
Q3.prototype.iu=function(){return!1};
Q3.prototype.Ne=function(){return!1};g.t(R3,g.V);g.h=R3.prototype;g.h.Pl=function(){this.C&&(this.F.stop(),this.La(this.D),this.D=null,this.C.close(),this.C=null)};
g.h.oy=function(){g.UC(this,this.l.Ne())};
g.h.NJ=function(){window.focus();this.Pl()};
g.h.hide=function(){g.V.prototype.hide.call(this)};
g.h.Jo=function(a){a=a||g.Q(g.W(this.l).experiments,"autoplay_time")||1E4;var b=Math.min(g.N()-this.H,a);a=Math.min(b/a,1);this.I.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.l.getPresentingPlayerType()?V3(this,!0):this.o&&this.o.start()};
g.h.VJ=function(a){!g.$d(this.A.element,g.Tr(a))&&g.cS(a,this.l)&&V3(this)};
g.h.iI=function(){g.dK(this.l,!0)};
g.h.nJ=function(a){this.l.getPresentingPlayerType();this.show();S3(this,a)};
g.h.OA=function(a){this.l.getPresentingPlayerType();this.u&&this.u.oa().videoId==a.oa().videoId||(this.u=a,P3(this,a,"hqdefault.jpg"))};
g.h.oJ=function(){this.l.getPresentingPlayerType();T3(this);this.hide()};
g.h.T=function(){T3(this);this.Pl();g.V.prototype.T.call(this)};g.t(W3,Q3);g.t(X3,g.V);X3.prototype.D=function(a){g.cS(a,this.l,this.A,this.o.Rb||void 0)&&Y3(this)};
X3.prototype.F=function(a){switch(a.keyCode){case 13:case 32:g.Yr(a)||(Y3(this),g.Xr(a))}};
X3.prototype.C=function(){var a=this.l.getVideoData(),b=g.W(this.l);this.A=a.Mb?!1:b.i};g.t(Z3,Q3);g.h=Z3.prototype;g.h.create=function(){Q3.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.A=a4(this,a),this.u=a);this.Jf();this.ba.K(this.player,"appresize",this.Jf);this.ba.K(this.player,"onVideoAreaChange",this.Jf);this.ba.K(this.player,"videodatachange",this.AF);this.ba.K(this.player,"autonavchange",this.Pq);this.ba.K(this.player,"autonavcancel",this.xF);a=this.u.autonavState;a!=this.O&&this.Pq(a);this.ba.K(this.element,"transitionend",this.kL)};
g.h.destroy=function(){g.Bs(this.ba);g.sf(this.o);this.o=[];this.A=null;Q3.prototype.destroy.call(this);g.Wn(this.element,"ytp-show-tiles");this.I.stop();this.O=this.u.autonavState};
g.h.iu=function(){return 1!=this.u.autonavState};
g.h.show=function(){Q3.prototype.show.call(this);g.Wn(this.element,"ytp-show-tiles");g.W(this.player).g?g.go(this.I):this.I.start();(this.F||this.D&&this.D!=this.u.clientPlaybackNonce)&&g.dK(this.player,!1);$3(this)?(b4(this),2==this.u.autonavState?g.P(g.W(this.player).experiments,"fast_autonav_in_background")&&3==this.player.getVisibilityState()?V3(this.l,!0):S3(this.l):3==this.u.autonavState&&U3(this.l)):(g.dK(this.player,!0),b4(this))};
g.h.hide=function(){Q3.prototype.hide.call(this);U3(this.l);b4(this)};
g.h.kL=function(a){g.Tr(a)==this.element&&this.Jf()};
g.h.Jf=function(){if(this.A&&this.A.length){g.I(this.element,"ytp-endscreen-paginate");var a=g.lK(this.H,!0),b=g.jD(this.H);b&&(b=b.Zb()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.A.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var q=b/2,r=e/2,u=b<=f-2&&n>=r*m,z=e<=k-2&&n>=q*m;if((q+1)/r*d/c>c/(q/(r+1)*d)&&z)n-=q*m,e+=2;else if(u)n-=r*m,b+=2;else if(z)n-=q*m,e+=2;else break}d=
!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.pd(a.width/m||1,1,1.21);n*=g.pd(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.M.element;g.Sh(a,m,n);g.Ah(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.l;f=this.A[0];c.u=f;P3(c,f,"hqdefault.jpg");g.J(this.element,"ytp-endscreen-takeover",$3(this));b4(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(q=c,r=0,d&&f>=b-2&&k>=e-
2?r=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(r=2):r=2),q=g.qd(q+this.C,l),0!=r){u=this.o[c];u||(u=new X3(this.player),this.o[c]=u,a.appendChild(u.element));z=Math.floor(n*k/e);var C=Math.floor(m*f/b),E=Math.floor(n*(k+r)/e)-z-4,F=Math.floor(m*(f+r)/b)-C-4;g.Ih(u.element,C,z);g.Sh(u.element,F,E);g.Ah(u.element,"transitionDelay",(k+f)/20+"s");g.J(u.element,"ytp-videowall-still-mini",1==r);g.J(u.element,"ytp-videowall-still-large",2<r);r=u;q=this.A[q];r.o!=q&&(r.o=q,P3(r,q,g.Un(r.element,"ytp-videowall-still-large")?
"hqdefault.jpg":"mqdefault.jpg"),q=(q=q.Rb)&&q.itct)&&(u=r.l,g.W(u).F&&g.gO(u.app.R,r.element,q));c++}g.J(this.element,"ytp-endscreen-paginate",c<l);for(b=this.o.length-1;b>=c;b--)e=this.o[b],g.Wd(e.element),g.rf(e);this.o.length=c}};
g.h.AF=function(){var a=this.player.getVideoData();this.u!=a&&(this.C=0,this.A=a4(this,a),this.u=a,this.Jf())};
g.h.yF=function(){this.C+=this.o.length;this.Jf()};
g.h.zF=function(){this.C-=this.o.length;this.Jf()};
g.h.aE=function(){return!!this.l.o};
g.h.Pq=function(a){1==a?(this.F=!1,this.D=this.u.clientPlaybackNonce,T3(this.l),this.Ea()&&this.Jf()):(this.F=!0,this.Ea()&&$3(this)&&(2==a?S3(this.l):3==a&&U3(this.l)))};
g.h.xF=function(a){if(a){for(a=0;a<this.o.length;a++)g.yK(this.H,this.o[a].element,!0);this.Pq(1)}else this.D=null,this.F=!1;this.Jf()};
g.h.Ne=function(){return this.Ea()&&$3(this)};g.t(d4,g.IK);g.h=d4.prototype;g.h.Nk=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!c4(this.player)||b;a=a.Lc||g.My(a.Na);var c=g.CX(this.player.app);return b&&!a&&!c};
g.h.Ne=function(){return this.g.Ne()};
g.h.VD=function(){return this.Ne()?this.g.aE():!1};
g.h.T=function(){g.qK(this.player,"endscreen");g.IK.prototype.T.call(this)};
g.h.load=function(){g.IK.prototype.load.call(this);this.g.show()};
g.h.unload=function(){g.IK.prototype.unload.call(this);this.g.hide();this.g.destroy()};
g.h.LE=function(a){this.Nk()&&(this.g.created||this.g.create(),"load"==a.getId()&&this.load())};
g.h.ME=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.Lz=function(){g.qK(this.player,"endscreen");var a=this.player.getVideoData();a=new g.SD(Math.max(1E3*(a.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});g.D(this,a);var b=new g.SD(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.D(this,b);g.nK(this.player,[a,b])};g.dV.endscreen=d4;})(_yt_player);
