(function(g){var window=this;var cqa=function(a,b){return g.Ub(a,b)},o5=function(){},dqa=function(a){if(a.xc&&"function"==typeof a.xc)return a.xc();
if(g.Ea(a))return a.split("");if(g.Ma(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Qb(a)},eqa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Ma(a)||g.Ea(a))(0,g.A)(a,b,void 0);else{if(a.Gd&&"function"==typeof a.Gd)var c=a.Gd();else if(a.xc&&"function"==typeof a.xc)c=void 0;else if(g.Ma(a)||g.Ea(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Rb(a);d=dqa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},p5=function(a){g.Ym(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.G)()).toString(36));
return a},q5=function(a,b,c){g.La(c)||(c=[String(c)]);
g.cn(a.l,b,c)},r5=function(a){return(a=g.wo(a))?new ActiveXObject(a):new XMLHttpRequest},s5=function(a,b){return b+" ["+a.aa+" "+a.D+" "+a.getStatus()+"]"},fqa=function(a){return"content-type"==a.toLowerCase()},t5=function(a){a.g&&a.I&&(a.g.ontimeout=null);
a.F&&(g.v.clearTimeout(a.F),a.F=null)},gqa=function(a){return g.Ld&&g.nd(9)&&g.Ga(a.timeout)&&g.Da(a.ontimeout)},u5=function(a){a.O||(a.O=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},v5=function(a,b){if(a.g){t5(a);
var c=a.g,d=a.P[0]?g.Ia:null;a.g=null;a.P=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},w5=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.u=5;u5(a);v5(a)},x5=function(a){return a.g?a.g.readyState:0},y5=function(a){if(a.i&&"undefined"!=typeof g.rY)if(a.P[1]&&4==x5(a)&&2==a.getStatus())s5(a,"Local request error detected and ignored");
else if(a.C&&4==x5(a))g.Hg(a.Tv,0,a);else if(a.dispatchEvent("readystatechange"),4==x5(a)){s5(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Tg(1,String(a.D));if(!f&&g.v.self&&g.v.self.location){var k=g.v.self.location.protocol;f=k.substr(0,k.length-1)}e=!hqa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.u=6;try{var l=2<x5(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";u5(a)}}finally{v5(a)}}},z5=function(a){g.Tf.call(this);
this.headers=new g.Nm;this.M=a||null;this.i=!1;this.P=this.g=null;this.aa=this.D="";this.u=0;this.l="";this.o=this.V=this.C=this.O=!1;this.A=0;this.F=null;this.Z="";this.I=this.R=!1},A5=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},iqa=function(a,b){var c=[];
g.Nk(b,function(d){try{var e=g.Lo.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Da(e)?g.Ko(e)&&c.push(d):c.push(d)},a);
return c},jqa=function(a,b){var c=iqa(a,b);
(0,g.A)(c,function(d){g.Lo.prototype.remove.call(this,d)},a)},B5=function(a){if(a.dd){if(a.dd.locationOverrideToken)return{locationOverrideToken:a.dd.locationOverrideToken};
if(null!=a.dd.latitudeE7&&null!=a.dd.longitudeE7)return{latitudeE7:a.dd.latitudeE7,longitudeE7:a.dd.longitudeE7}}return null},kqa=function(a,b){g.$a(a,b)||a.push(b)},C5=function(a){var b=0,c;
for(c in a)b++;return b},D5=function(a,b){var c=b instanceof g.xc?b:g.Dc(b,/^data:image\//i.test(b));
a.src=g.yc(c)},lqa=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},mqa=function(a,b,c,d){var e=new g.Qm(null,void 0);
a&&g.Rm(e,a);b&&g.Sm(e,b);c&&g.Tm(e,c);d&&(e.i=d);return e},E5=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return lqa(a)},F5=function(){this.g=[];
this.i=[]},G5=function(a,b){g.Qp[a]=!0;
var c=g.Op();c&&c.publish.apply(c,arguments);g.Qp[a]=!1},H5=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Nm;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",nqa(this,a.capabilities||""),oqa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},nqa=function(a,b){a.capabilities.clear();
(0,g.Xd)(b.split(","),g.Ra(cqa,pqa)).forEach(function(c){a.capabilities.add(c)})},oqa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},I5=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},J5=function(a,b){return!!b&&(a.id==b||a.uuid==b)},K5=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},qqa=function(a){return new I5(a)},L5=function(a){return g.La(a)?(0,g.ge)(a,qqa):[]},M5=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},N5=function(a){return g.La(a)?"["+(0,g.ge)(a,M5).join(",")+"]":"null"},O5=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},rqa=function(a){return(0,g.ge)(a,function(b){return{key:b.id,
name:b.name}})},P5=function(a,b){return g.Xa(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},Q5=function(a,b){return g.Xa(a,function(c){return J5(c,b)})},R5=function(a){try{var b=(0,g.it)(),c=(0,g.ht)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},sqa=function(){var a=(0,g.ht)();
a&&jqa(a,a.g.lf(!0))},S5=function(){var a=g.kt("yt-remote-connected-devices")||[];
g.qb(a);return a},tqa=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.ge)(a,function(d,e){return 0==e?d:d.substring(c.length)})},T5=function(a){g.jt("yt-remote-connected-devices",a,86400)},V5=function(){if(U5)return U5;
var a=g.kt("yt-remote-device-id");a||(a=O5(),g.jt("yt-remote-device-id",a,31536E3));for(var b=S5(),c=1,d=a;g.$a(b,d);)c++,d=a+"#"+c;return U5=d},W5=function(){var a=S5(),b=V5();
g.$a(a,b);g.lt()&&g.sb(a,b);a=tqa(a);if(0==a.length)try{g.ls("remote_sid")}catch(c){}else try{g.ks("remote_sid",a.join(","),-1)}catch(c){}},X5=function(){return g.kt("yt-remote-session-browser-channel")},Y5=function(){return g.kt("yt-remote-local-screens")||[]},Z5=function(){g.jt("yt-remote-lounge-token-expiration",!0,86400)},uqa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.ge)(Y5(),function(d){return d.loungeToken}),c=(0,g.ge)(a,function(d){return d.loungeToken});
(0,g.lj)(c,function(d){return!g.$a(b,d)})&&Z5();
g.jt("yt-remote-local-screens",a,31536E3)},vqa=function(a,b){g.jt("yt-remote-session-browser-channel",a);
g.jt("yt-remote-session-screen-id",b);var c=S5(),d=V5();g.$a(c,d)||c.push(d);T5(c);W5()},$5=function(a){a||(R5("yt-remote-session-screen-id"),R5("yt-remote-session-video-id"));
W5();a=S5();g.cb(a,V5());T5(a)},b6=function(){if(!a6){var a=g.Vo();
a&&(a6=new g.Fo(a))}return a6?!!a6.get("yt-remote-use-staging-server"):!1},wqa=function(){var a=g.Dp("PLAYER_CONFIG");
return a&&a.args&&void 0!==a.args.authuser?!0:!(!g.Dp("SESSION_INDEX")&&!g.Dp("LOGGED_IN"))},c6=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},d6=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},f6=function(a){a.length?e6(a.shift(),function(){f6(a)}):g6()},xqa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},e6=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},g6=function(){var a=d6();
a&&a(!1,"No cast extension found")},h6=function(){if(yqa){var a=2,b=d6(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;e6("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",g6,c)}},zqa=function(){h6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);f6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},i6=function(a,b,c){g.B.call(this);
this.A=null!=c?(0,g.x)(a,c):a;this.Wc=b;this.u=(0,g.x)(this.gD,this);this.g=!1;this.i=0;this.l=this.za=null;this.o=[]},j6=function(){},k6=function(a,b,c,d){this.g=a;
this.l=b;this.C=c;this.A=d||1;this.o=45E3;this.ba=new g.dn(this);this.i=new g.Gg;this.i.setInterval(250)},m6=function(a,b,c){a.Vh=1;
a.Wf=p5(b.clone());a.sh=c;a.u=!0;l6(a,null)},n6=function(a,b,c,d,e){a.Vh=1;
a.Wf=p5(b.clone());a.sh=null;a.u=c;e&&(a.Rz=!1);l6(a,d)},l6=function(a,b){a.Fi=(0,g.G)();
o6(a);a.Dg=a.Wf.clone();q5(a.Dg,"t",a.A);a.bl=0;a.qc=a.g.lp(a.g.Pk()?b:null);0<a.Pp&&(a.Gn=new g.Dl((0,g.x)(a.YA,a,a.qc),a.Pp));a.ba.ca(a.qc,"readystatechange",a.UL);var c=a.Zg?g.bc(a.Zg):{};a.sh?(a.lo="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.qc.send(a.Dg,a.lo,a.sh,c)):(a.lo="GET",a.Rz&&!g.Nd&&(c.Connection="close"),a.qc.send(a.Dg,a.lo,null,c));a.g.se(1)},v6=function(a,b,c){for(var d=!0;!a.Og&&a.bl<c.length;){var e=Aqa(a,c);
if(e==p6){4==b&&(a.pg=4,q6(15),d=!1);break}else if(e==r6){a.pg=4;q6(16);d=!1;break}else s6(a,e)}4==b&&0==c.length&&(a.pg=1,q6(17),d=!1);a.we=a.we&&d;d||(t6(a),u6(a))},Aqa=function(a,b){var c=a.bl,d=b.indexOf("\n",c);
if(-1==d)return p6;c=Number(b.substring(c,d));if(isNaN(c))return r6;d+=1;if(d+c>b.length)return p6;var e=b.substr(d,c);a.bl=d+c;return e},y6=function(a,b){a.Fi=(0,g.G)();
o6(a);var c=b?window.location.hostname:"";a.Dg=a.Wf.clone();g.Ym(a.Dg,"DOMAIN",c);g.Ym(a.Dg,"t",a.A);try{a.Be=new ActiveXObject("htmlfile")}catch(n){t6(a);a.pg=7;q6(22);u6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in w6)k=w6[l];else if(l in x6)k=w6[l]=x6[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
w6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Rc(g.qc("b/12014412"),d+"</body></html>");a.Be.open();a.Be.write(g.Mc(c));a.Be.close();a.Be.parentWindow.m=(0,g.x)(a.nL,a);a.Be.parentWindow.d=(0,g.x)(a.Wy,a,!0);a.Be.parentWindow.rpcClose=(0,g.x)(a.Wy,a,!1);c=a.Be.createElement("DIV");a.Be.parentWindow.document.body.appendChild(c);d=g.Cc(a.Dg.toString());d=g.Yc(g.zc(d));d=g.Rc(g.qc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Sc(c,d);a.g.se(1)},o6=function(a){a.Rs=(0,g.G)()+a.o;
z6(a,a.o)},z6=function(a,b){if(null!=a.Wi)throw Error("WatchDog timer not null");
a.Wi=A6((0,g.x)(a.xL,a),b)},B6=function(a){a.Wi&&(g.v.clearTimeout(a.Wi),a.Wi=null)},u6=function(a){a.g.Rv()||a.Og||a.g.un(a)},t6=function(a){B6(a);
g.rf(a.Gn);a.Gn=null;a.i.stop();g.fn(a.ba);if(a.qc){var b=a.qc;a.qc=null;b.abort();b.dispose()}a.Be&&(a.Be=null)},s6=function(a,b){try{a.g.Qy(a,b),a.g.se(4)}catch(c){}},D6=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;C6(a,b,function(k){k?c(!0):g.v.setTimeout(function(){D6(a,b,c,d,f)},f)})}},C6=function(a,b,c){var d=new Image;
d.onload=function(){try{E6(d),c(!0)}catch(e){}};
d.onerror=function(){try{E6(d),c(!1)}catch(e){}};
d.onabort=function(){try{E6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{E6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
D5(d,a)},E6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},F6=function(a){this.g=a;
this.i=new j6},H6=function(a){var b=G6(a.g,a.ij,"/mail/images/cleardot.gif");
p5(b);D6(b.toString(),5E3,(0,g.x)(a.oC,a),3,2E3);a.se(1)},J6=function(a){var b=a.g.F;
if(null!=b)q6(5),b?(q6(11),I6(a.g,a,!1)):(q6(12),I6(a.g,a,!0));else if(a.Bd=new k6(a,void 0,void 0,void 0),a.Bd.Zg=a.Mp,b=a.g,b=G6(b,b.Pk()?a.Qj:null,a.Op),q6(5),!g.Ld||g.od(10))q5(b,"TYPE","xmlhttp"),n6(a.Bd,b,!1,a.Qj,!1);else{q5(b,"TYPE","html");var c=a.Bd;a=!!a.Qj;c.Vh=3;c.Wf=p5(b.clone());y6(c,a)}},K6=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.u=new j6;this.D=a||null;this.F=null!=b?b:null;this.A=c||!1},Bqa=function(a,b){this.g=a;
this.map=b;this.context=null},L6=function(a){g.tf.call(this,"statevent",a)},M6=function(a,b){g.tf.call(this,"timingevent",a);
this.size=b},N6=function(a){g.tf.call(this,"serverreachability",a)},R6=function(a){O6(a);
if(3==a.g){var b=a.wk++,c=a.fm.clone();g.Ym(c,"SID",a.l);g.Ym(c,"RID",b);g.Ym(c,"TYPE","terminate");P6(a,c);b=new k6(a,a.l,b,void 0);b.Vh=2;b.Wf=p5(c.clone());D5(new Image,b.Wf.toString());b.Fi=(0,g.G)();o6(b)}Q6(a)},T6=function(a){a.FC(1,0);
a.fm=G6(a,null,a.Lp);S6(a)},O6=function(a){a.eg&&(a.eg.abort(),a.eg=null);
a.Sb&&(a.Sb.cancel(),a.Sb=null);a.nf&&(g.v.clearTimeout(a.nf),a.nf=null);U6(a);a.xd&&(a.xd.cancel(),a.xd=null);a.lg&&(g.v.clearTimeout(a.lg),a.lg=null)},V6=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new Bqa(a.DH++,b));2!=a.g&&3!=a.g||S6(a)},S6=function(a){a.xd||a.lg||(a.lg=A6((0,g.x)(a.Vy,a),0),a.Ph=0)},Y6=function(a,b){if(1==a.g){if(!b){a.wk=Math.floor(1E5*Math.random());
var c=a.wk++,d=new k6(a,"",c,void 0);d.Zg=null;var e=W6(a),f=a.fm.clone();g.Ym(f,"RID",c);g.Ym(f,"CVER","1");P6(a,f);m6(d,f,e);a.xd=d;a.g=2}}else 3==a.g&&(b?X6(a,b):0==a.i.length||a.xd||X6(a))},X6=function(a,b){if(b)if(6<a.Pg){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.wk-1;var d=W6(a)}else c=b.C,d=b.sh;else c=a.wk++,d=W6(a);var e=a.fm.clone();g.Ym(e,"SID",a.l);g.Ym(e,"RID",c);g.Ym(e,"AID",a.ii);P6(a,e);c=new k6(a,a.l,c,a.Ph+1);c.Zg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.xd=c;m6(c,e,d)},P6=function(a,b){if(a.Tc){var c=a.Tc.tv();
c&&g.Kb(c,function(d,e){g.Ym(b,e,d)})}},W6=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Pg&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Pg?e:f-d;try{g.Kb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},Z6=function(a){a.Sb||a.nf||(a.C=1,a.nf=A6((0,g.x)(a.Uy,a),0),a.Ih=0)},a7=function(a){if(a.Sb||a.nf||3<=a.Ih)return!1;
a.C++;a.nf=A6((0,g.x)(a.Uy,a),$6(a,a.Ih));a.Ih++;return!0},I6=function(a,b,c){a.jo=c;
a.Je=b.yf;a.A||T6(a)},U6=function(a){null!=a.Tg&&(g.v.clearTimeout(a.Tg),a.Tg=null)},$6=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},c7=function(a,b){if(2==b||9==b){var c=null;
a.Tc&&(c=null);var d=(0,g.x)(a.yM,a);c||(c=new g.Qm("//www.google.com/images/cleardot.gif"),p5(c));C6(c.toString(),1E4,d)}else q6(2);b7(a,b)},b7=function(a,b){a.g=0;
a.Tc&&a.Tc.vu(b);Q6(a);O6(a)},Q6=function(a){a.g=0;
a.Je=-1;if(a.Tc)if(0==a.o.length&&0==a.i.length)a.Tc.Yo();else{g.fb(a.o);var b=g.fb(a.i);a.o.length=0;a.i.length=0;a.Tc.Yo(b)}},G6=function(a,b,c){var d=g.Zm(c);
if(""!=d.g)b&&g.Sm(d,b+"."+d.g),g.Tm(d,d.u);else{var e=window.location;d=mqa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.xj&&g.Kb(a.xj,function(f,k){g.Ym(d,k,f)});
g.Ym(d,"VER",a.Pg);P6(a,d);return d},A6=function(a,b){if(!g.Na(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},q6=function(a){d7.dispatchEvent(new L6(d7,a))},e7=function(){},Cqa=function(a,b){this.action=a;
this.params=b||{}},f7=function(a,b){g.B.call(this);
this.g=new g.K(this.fL,0,this);g.D(this,this.g);this.Wc=5E3;this.i=0;if(g.Na(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Na(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},g7=function(a,b,c){this.H=a;
this.A=b;this.l=new g.Eo;this.i=new f7(this.dM,this);this.g=null;this.fb=!1;this.u=null;this.F="";this.D=this.o=0;this.C=[];this.I=c||!1},Dqa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.jo,sessionId:a.g.l,arrayId:a.g.ii}},h7=function(a,b){a.D=b||0;
a.i.stop();a.g&&(3==a.g.g&&Y6(a.g),R6(a.g));a.D=0},i7=function(a){return!!a.g&&3==a.g.g},Eqa=function(a,b){(a.A.loungeIdToken=b)||a.i.stop()},j7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=Number(g.Tg(4,a))||"";b&&(this.port=":"+b);this.domain=g.Ug(a)||"";a=g.Ib;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Hb(a,"10.0")&&(this.i=!1))},k7=function(a,b){var c=a.g;
if(g.Da(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.dh(c+b,{})},l7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ra(a.o,d,!0),onError:g.Ra(a.l,e),he:g.Ra(a.u,e)};c&&(a.ub=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Iq(b,a)},Fqa=function(){var a=m7;
n7();o7.push(a);p7(o7)},q7=function(a,b){n7();
var c=o7,d=Gqa(a,String(b));0==c.length?Hqa(d):(p7(c),(0,g.A)(c,function(e){e(d)}))},n7=function(){o7||(o7=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ha("yt.mdx.remote.debug.handlers_",o7,void 0))},Hqa=function(a){var b=(r7+1)%50;
r7=b;s7[b]=a;t7||(t7=49==b)},p7=function(a){var b=s7;
if(b[0]){var c=r7,d=t7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.A)(a,function(f){f(e)})}while(d!=c);
s7=Array(50);r7=-1;t7=!1}},Gqa=function(a,b){var c=((0,g.G)()-Iqa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},u7=function(a){g.O.call(this);
this.C=a;this.g=[]},v7=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},Jqa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Xd)(a.g,function(f){return!!P5(b,f)});
for(var d=0,e=b.length;d<e;d++)c=v7(a,b[d])||c;return c},Kqa=function(a,b){var c=a.g.length;
a.g=(0,g.Xd)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},w7=function(a,b,c,d){g.O.call(this);
this.A=a;this.u=b;this.l=c;this.o=d;this.i=0;this.g=null;this.za=NaN},y7=function(a){u7.call(this,"LocalScreenService");
this.l=a;this.i=NaN;x7(this);this.info("Initializing with "+N5(this.g))},z7=function(a){if(a.g.length){var b=(0,g.ge)(a.g,function(d){return d.id}),c=k7(a.l,"/pairing/get_lounge_token_batch");
l7(a.l,c,{screen_ids:b.join(",")},(0,g.x)(a.qD,a),(0,g.x)(a.pD,a))}},x7=function(a){var b=L5(Y5());
b=(0,g.Xd)(b,function(c){return!c.uuid});
return Jqa(a,b)},A7=function(a,b){uqa((0,g.ge)(a.g,K5));
b&&Z5()},C7=function(a,b){g.O.call(this);
this.A=b;var c=g.kt("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.A(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.$a(c,l)}this.g=d;this.u=a;this.l=this.o=NaN;this.i=null;B7("Initialized with "+g.Lg(this.g))},D7=function(a,b,c){var d=k7(a.u,"/pairing/get_screen_availability");
l7(a.u,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},E7=function(a,b){a:if(C5(b)!=C5(a.g))var c=!1;
else{c=g.Rb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(B7("Updated online screens: "+g.Lg(a.g)),a.g=b,a.N("screenChange"));Lqa(a)},F7=function(a){isNaN(a.l)||g.Np(a.l);
a.l=g.Lp((0,g.x)(a.Tr,a),0<a.o&&a.o<(0,g.G)()?2E4:1E4)},B7=function(a){q7("OnlineScreenService",a)},G7=function(a){var b={};
(0,g.A)(a.A(),function(c){c.token?b[c.token]=c.id:this.Hb("Requesting availability of screen w/o lounge token.")});
return b},Lqa=function(a){a=g.Rb(g.Lb(a.g,function(b){return b}));
g.qb(a);a.length?g.jt("yt-remote-online-screen-ids",a.join(","),60):R5("yt-remote-online-screen-ids")},H7=function(a){u7.call(this,"ScreenService");
this.A=a;this.i=this.l=null;this.o=[];this.u={};Mqa(this)},J7=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.u[b]);var k=a.Hd();if(k=(c?Q5(k,c):null)||Q5(k,b)){k.uuid=b;var l=I7(a,k);D7(a.i,l,function(m){e(m?l:null)})}else c?Nqa(a,c,(0,g.x)(function(m){var n=I7(this,new I5({name:d,
screenId:c,loungeToken:m,dialId:b||""}));D7(this.i,n,function(q){e(q?n:null)})},a),f):e(null)},K7=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},Nqa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={ub:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Iq(k7(a.A,"/pairing/get_lounge_token_batch"),e)},L7=function(a){a.g=a.l.Hd();
var b=a.u,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+N5(a.g))},Mqa=function(a){M7(a);
a.l=new y7(a.A);a.l.subscribe("screenChange",(0,g.x)(a.yD,a));L7(a);a.o=L5(g.kt("yt-remote-automatic-screen-cache")||[]);M7(a);a.info("Initializing automatic screens: "+N5(a.o));a.i=new C7(a.A,(0,g.x)(a.Hd,a,!0));a.i.subscribe("screenChange",(0,g.x)(function(){this.N("onlineScreenChange")},a))},I7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=Q5(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.jt("yt-remote-automatic-screen-cache",(0,g.ge)(a.o,K5)));M7(a);a.u[b.uuid]=b.id;g.jt("yt-remote-device-id-map",a.u,31536E3);return b},M7=function(a){a.u=g.kt("yt-remote-device-id-map")||{}},N7=function(a,b,c){g.O.call(this);
this.P=c;this.F=a;this.i=b;this.l=null},O7=function(a,b){q7(a.P,b)},Q7=function(a,b){N7.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.A=(0,g.x)(this.eN,this);this.u=(0,g.x)(this.IL,this);this.o=g.Lp((0,g.x)(function(){P7(this,null)},this),12E4)},Oqa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Lg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ia,(0,g.x)(function(){O7(this,"Failed to send message: getMdxSessionStatus.")},a)):O7(a,"Sending yt message without session: "+g.Lg(b))},P7=function(a,b){g.Np(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.x)(a.wn,a),d=(0,g.x)(a.Ld,a);a.Jv(b,c,d,5)}}else a.Ld(Error("Waiting for session status timed out."))},R7=function(a,b,c){N7.call(this,a,b,"DialSession");
this.o=this.D=null;this.H="";this.M=c;this.u=null;this.C=g.Ia;this.A=NaN;this.I=(0,g.x)(this.hN,this);this.g=g.Ia},S7=function(a){a.g=a.F.dB(a.H,a.i.label,a.i.friendlyName,(0,g.x)(function(b){this.g=g.Ia;
this.wn(b)},a),(0,g.x)(function(b){this.g=g.Ia;
this.Ld(b)},a))},T7=function(a){var b={};
b.pairingCode=a.H;b.theme=a.M;if(a.u){var c=a.u.currentTime||0;b.v=a.u.videoId;b.t=c}b6()&&(b.env_useStageMdx=1);return g.bh(b)},U7=function(a,b){N7.call(this,a,b,"ManualSession");
this.g=g.Lp((0,g.x)(this.ki,this,null),150)},V7=function(a,b,c,d){g.O.call(this);
this.i=a;this.C=b||"233637DE";this.A=c||"cl";this.D=d||!1;this.g=null;this.u=!1;this.l=[];this.o=(0,g.x)(this.oK,this)},W7=function(a,b){return b?g.Xa(a.l,function(c){return J5(b,c.label)},a):null},X7=function(a){q7("Controller",a)},m7=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},Y7=function(a){return a.u||!!a.l.length||!!a.g},Z7=function(a,b,c){b!=a.g&&(g.rf(a.g),(a.g=b)?(c?a.N("yt-remote-cast2-receiver-resumed",b.i):a.N("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.x)(a.Ty,a,b)),b.l?a.N("yt-remote-cast2-session-change",b.l):c&&a.g.ki(null)):a.N("yt-remote-cast2-session-change",null))},$7=function(a){var b=a.i.cB(),c=a.g&&a.g.i;
a=(0,g.ge)(b,function(d){c&&J5(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=W7(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Sqa=function(a,b,c,d,e,f,k){Pqa()?Qqa(b,e,f,k)&&(b8(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?c8(a,c):(window.__onGCastApiAvailable=function(l,m){l?c8(a,c):(d8("Failed to load cast API: "+m),e8(!1),b8(!1),R5("yt-remote-cast-available"),R5("yt-remote-cast-receiver"),f8(),c(!1))},d?g.Yp("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?zqa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?g6():(h6(),f6(Rqa.map(xqa))))):a8("Cannot initialize because not running Chrome")},f8=function(){a8("dispose");
var a=g8();a&&a.dispose();g.Ha("yt.mdx.remote.cloudview.instance_",null,void 0);h8(!1);g.Tp(i8);i8.length=0},j8=function(){return!!g.kt("yt-remote-cast-installed")},k8=function(){var a=g.kt("yt-remote-cast-receiver");
return a?a.friendlyName:null},l8=function(){a8("clearCurrentReceiver");
R5("yt-remote-cast-receiver")},m8=function(){return j8()?g8()?g8().getCastSession():(d8("getCastSelector: Cast is not initialized."),null):(d8("getCastSelector: Cast API is not installed!"),null)},o8=function(){j8()?g8()?n8()?(a8("Requesting cast selector."),g8().requestSession()):(a8("Wait for cast API to be ready to request the session."),i8.push(g.Sp("yt-remote-cast2-api-ready",o8))):d8("requestCastSelector: Cast is not initialized."):d8("requestCastSelector: Cast API is not installed!")},p8=function(a,
b){n8()?g8().setConnectedScreenStatus(a,b):d8("setConnectedScreenStatus called before ready.")},Pqa=function(){var a=0<=g.Ib.search(/ (CrMo|Chrome|CriOS)\//);
return g.Uw||a},Tqa=function(a,b){g8().init(a,b)},Qqa=function(a,b,c,d){var e=!1;
g8()||(a=new V7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.jt("yt-remote-cast-available",f);G5("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){a8("onReceiverSelected: "+f.friendlyName);
g.jt("yt-remote-cast-receiver",f);G5("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){a8("onReceiverResumed: "+f.friendlyName);
g.jt("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){a8("onSessionChange: "+M5(f));
f||R5("yt-remote-cast-receiver");G5("yt-remote-cast2-session-change",f)}),g.Ha("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
a8("cloudview.createSingleton_: "+e);return e},g8=function(){return g.w("yt.mdx.remote.cloudview.instance_")},c8=function(a,b){e8(!0);
b8(!1);Tqa(a,function(c){c?(h8(!0),g.Vp("yt-remote-cast2-api-ready")):(d8("Failed to initialize cast API."),e8(!1),R5("yt-remote-cast-available"),R5("yt-remote-cast-receiver"),f8());b(c)})},a8=function(a){q7("cloudview",a)},d8=function(a){q7("cloudview",a)},e8=function(a){a8("setCastInstalled_ "+a);
g.jt("yt-remote-cast-installed",a)},n8=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},h8=function(a){a8("setApiReady_ "+a);
g.Ha("yt.mdx.remote.cloudview.apiReady_",a,void 0)},b8=function(a){g.Ha("yt.mdx.remote.cloudview.initializing_",a,void 0)},q8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.A=this.C=0;this.g=null;this.hasNext=this.Ke=!1;this.F=this.D=this.i=this.o=0;this.l=NaN;this.u=!1;this.reset(a)},r8=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Ke=!1;a.hasNext=!1;a.C=0;a.A=(0,g.G)();a.o=0;a.i=0;a.D=0;a.F=0;a.l=NaN;a.u=!1},s8=function(a){return 1==a.playerState?((0,g.G)()-a.A)/1E3:0},t8=function(a,b){a.C=b;
a.A=(0,g.G)()},u8=function(a){switch(a.playerState){case 1:case 1081:return((0,g.G)()-a.A)/1E3+a.C;
case -1E3:return 0}return a.C},v8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&r8(a)},w8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.cc(a.g);b.hasPrevious=a.Ke;b.hasNext=a.hasNext;b.playerTime=a.C;b.playerTimeAt=a.A;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.F;b.liveIngestionTime=a.l;return b},z8=function(a,b){g.O.call(this);
this.g=0;this.o=a;this.A=[];this.u=new F5;this.l=this.i=null;this.F=(0,g.x)(this.lI,this);this.C=(0,g.x)(this.zk,this);this.D=(0,g.x)(this.kI,this);this.H=(0,g.x)(this.yI,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Us,this),x8(this))):c=3;0!=c&&(b?this.Us(c):g.Lp((0,g.x)(function(){this.Us(c)},this),0));
var d=m8();d&&y8(this,d);this.subscribe("yt-remote-cast2-session-change",this.H)},A8=function(a){return new q8(a.o.getPlayerContextData())},x8=function(a){(0,g.A)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.A.push(this.o.subscribe(b,g.Ra(this.lK,b),this))},a)},B8=function(a){(0,g.A)(a.A,function(b){this.o.unsubscribeByKey(b)},a);
a.A.length=0},C8=function(a,b){var c=a.u;
50>c.g.length+c.i.length&&a.u.i.push(b)},E8=function(a,b,c){var d=A8(a);
t8(d,c);-1E3!=d.playerState&&(d.playerState=b);D8(a,d)},F8=function(a,b,c){a.o.sendMessage(b,c)},D8=function(a,b){B8(a);
a.o.setPlayerContextData(w8(b));x8(a)},y8=function(a,b){a.l&&(a.l.removeUpdateListener(a.F),a.l.removeMediaListener(a.C),a.zk(null));
a.l=b;a.l&&(q7("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.F),a.l.addMediaListener(a.C),a.l.media.length&&a.zk(a.l.media[0]))},G8=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=A8(a);b.contentId!=d.videoId&&q7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;t8(d,a.i.getEstimatedTime());D8(a,d)}else q7("CP","No cast media video. Ignoring state update.")},H8=function(a,b,c){return(0,g.x)(function(d){this.Hb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Hb("Retrying "+b+" using MDx browser channel."),F8(this,b,c))},a)},I8=function(a,b,c){g.O.call(this);
this.u=NaN;this.I=!1;this.D=this.C=this.F=this.H=NaN;this.P=[];this.o=this.A=this.l=this.Oa=this.g=null;this.O=a;this.P.push(g.Rr(window,"beforeunload",(0,g.x)(this.jD,this)));this.i=[];this.Oa=new q8;this.M=b.id;this.g=Uqa(this,c);this.g.subscribe("handlerOpened",this.pI,this);this.g.subscribe("handlerClosed",this.mI,this);this.g.subscribe("handlerError",this.nI,this);this.g.subscribe("handlerMessage",this.oI,this);Eqa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Oa.videoId;
g.lt()&&g.jt("yt-remote-session-video-id",d)},this)},J8=function(a){q7("conn",a)},Uqa=function(a,b){return new g7(k7(a.O,"/bc"),b)},K8=function(a,b){a.N("proxyStateChange",b)},Vqa=function(a){a.u=g.Lp((0,g.x)(function(){J8("Connecting timeout");
this.Mh(1)},a),2E4)},L8=function(a){g.Np(a.u);
a.u=NaN},M8=function(a){g.Np(a.H);
a.H=NaN},Wqa=function(a){N8(a);
a.F=g.Lp((0,g.x)(function(){O8(this,"getNowPlaying")},a),2E4)},N8=function(a){g.Np(a.F);
a.F=NaN},Q8=function(a,b){b&&(L8(a),M8(a));
b==(i7(a.g)&&isNaN(a.u))?b&&(K8(a,1),O8(a,"getSubtitlesTrack")):b?(a.Gv()&&a.Oa.reset(),K8(a,1),O8(a,"getNowPlaying"),P8(a)):a.Mh(1)},Xqa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Oa.videoId&&(g.Xb(b.params)?a.Oa.g=null:a.Oa.g=b.params,a.N("remotePlayerChange"))},R8=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Oa.listId=b.params.listId||a.Oa.listId;v8(a.Oa,c,d);a.N("remoteQueueChange")},Yqa=function(a,b){b.params=b.params||{};
R8(a,b);S8(a,b);a.N("autoplayDismissed")},S8=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
t8(a.Oa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Oa.playerState&&(c=-1E3);a.Oa.playerState=c;c=Number(b.params.loadedTime);a.Oa.F=isNaN(c)?0:c;c=Number(b.params.duration);a.Oa.D=isNaN(c)?0:c;c=a.Oa;var d=Number(b.params.liveIngestionTime);c.l=d;c.u=isNaN(d)?!1:!0;c=a.Oa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Oa.playerState?Wqa(a):N8(a);a.N("remotePlayerChange")},Zqa=function(a,b){if(-1E3!=
a.Oa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Oa.playerState=c;c=parseInt(b.params.currentTime,10);t8(a.Oa,isNaN(c)?0:c);a.N("remotePlayerChange")}},$qa=function(a,b){var c="true"==b.params.muted;
a.Oa.volume=parseInt(b.params.volume,10);a.Oa.muted=c;a.N("remotePlayerChange")},ara=function(a,b){a.A=b.params.videoId;
a.N("nowAutoplaying",parseInt(b.params.timeout,10))},bra=function(a,b){var c="true"==b.params.hasNext;
a.Oa.Ke="true"==b.params.hasPrevious;a.Oa.hasNext=c;a.N("previousNextChange")},P8=function(a){g.Np(a.D);
a.D=g.Lp((0,g.x)(a.Mh,a,1),864E5)},O8=function(a,b,c){c?J8("Sending: action="+b+", params="+g.Lg(c)):J8("Sending: action="+b);
a.g.sendMessage(b,c)},T8=function(a){u7.call(this,"ScreenServiceProxy");
this.Vc=a;this.i=[];this.i.push(this.Vc.$_s("screenChange",(0,g.x)(this.cN,this)));this.i.push(this.Vc.$_s("onlineScreenChange",(0,g.x)(this.QJ,this)))},gra=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.Dp("MDX_CONFIG")||b;sqa();W5();U8||(U8=new j7(b?b.loungeApiHost:void 0),b6()&&(U8.g="/api/loungedev"));V8||(V8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ha("yt.mdx.remote.deferredProxies_",V8,void 0));cra();var c=W8();if(!c){var d=new H7(U8);g.Ha("yt.mdx.remote.screenService_",d,void 0);c=W8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Sqa(a,d,function(m){m?X8()&&p8(X8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){G5("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ha("yt.mdx.remote.initialized_",!0,void 0),Y8("Initializing: "+g.Lg(b)),Z8.push(g.Sp("yt-remote-cast2-availability-change",function(){G5("yt-remote-receiver-availability-change")})),Z8.push(g.Sp("yt-remote-cast2-receiver-selected",function(){$8(null);
G5("yt-remote-auto-connect","cast-selector-receiver")})),Z8.push(g.Sp("yt-remote-cast2-receiver-resumed",function(){G5("yt-remote-receiver-resumed","cast-selector-receiver")})),Z8.push(g.Sp("yt-remote-cast2-session-change",dra)),Z8.push(g.Sp("yt-remote-connection-change",function(m){m?p8(X8(),"YouTube TV"):a9()||(p8(null,null),l8())})),a=b9(),b.isAuto&&(a.id+="#dial"),g.zq("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),Y8(" -- with channel params: "+
g.Lg(a)),era(a),c.start(),X8()||fra())},ira=function(){var a=hra();
j8()&&g.kt("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},hra=function(){var a=W8().Vc.$_gos();
var b=c9();b&&d9()&&(P5(a,b)||a.push(b));return rqa(a)},e9=function(){var a=jra();
!a&&j8()&&k8()&&(a={key:"cast-selector-receiver",name:k8()});return a},jra=function(){var a=hra(),b=c9();
b||(b=a9());return g.Xa(a,function(c){return b&&J5(b,c.key)?!0:!1})},c9=function(){var a=X8();
if(!a)return null;var b=W8().Hd();return Q5(b,a)},dra=function(a){Y8("remote.onCastSessionChange_: "+M5(a));
if(a){var b=c9();b&&b.id==a.id?p8(b.id,"YouTube TV"):(b&&f9(),g9(a,1))}else d9()&&f9()},kra=function(a,b){Y8("Connecting to: "+g.Lg(a));
if("cast-selector-receiver"==a.key)$8(b||null),n8()?g8().setLaunchParams(b||null):d8("setLaunchParams called before ready.");else if(!b&&h9()&&X8()==a.key)G5("yt-remote-connection-change",!0);else{f9();$8(b||null);var c=W8().Hd();(c=Q5(c,a.key))&&g9(c,1)}},f9=function(){n8()?g8().stopSession():d8("stopSession called before API ready.");
var a=d9();a&&(a.disconnect(1),i9(null))},h9=function(){var a=d9();
return!!a&&3!=a.getProxyState()},Y8=function(a){q7("remote",a)},W8=function(){if(!j9){var a=g.w("yt.mdx.remote.screenService_");
j9=a?new T8(a):null}return j9},X8=function(){return g.w("yt.mdx.remote.currentScreenId_")},lra=function(a){g.Ha("yt.mdx.remote.currentScreenId_",a,void 0)},mra=function(){return g.w("yt.mdx.remote.connectData_")},$8=function(a){g.Ha("yt.mdx.remote.connectData_",a,void 0)},d9=function(){return g.w("yt.mdx.remote.connection_")},i9=function(a){var b=d9();
$8(null);a||lra("");g.Ha("yt.mdx.remote.connection_",a,void 0);V8&&((0,g.A)(V8,function(c){c(a)}),V8.length=0);
b&&!a?G5("yt-remote-connection-change",!1):!b&&a&&G5("yt-remote-connection-change",!0)},a9=function(){var a=g.lt();
if(!a)return null;var b=W8().Hd();return Q5(b,a)},g9=function(a,b){c9()&&c9();
if(k9)l9=a;else{lra(a.id);var c=new I8(U8,a,b9());c.connect(b,mra());c.subscribe("beforeDisconnect",function(d){G5("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){d9()&&i9(null)});
i9(c)}},fra=function(){var a=a9();
a?(Y8("Resume connection to: "+M5(a)),g9(a,0)):($5(),l8(),Y8("Skipping connecting because no session screen found."))},cra=function(){var a=b9();
if(g.Xb(a)){a=V5();var b=g.kt("yt-remote-session-name")||"",c=g.kt("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ha("yt.mdx.remote.channelParams_",a,void 0)}},b9=function(){return g.w("yt.mdx.remote.channelParams_")||{}},era=function(a){a?(g.jt("yt-remote-session-app",a.app),g.jt("yt-remote-session-name",a.name)):(R5("yt-remote-session-app"),R5("yt-remote-session-name"));
g.Ha("yt.mdx.remote.channelParams_",a,void 0)},m9=function(a,b,c){g.B.call(this);
this.u=a;this.i=b;this.l=new g.zs(this);g.D(this,this.l);this.l.K(b,"onCaptionsTrackListChanged",this.kJ);this.l.K(b,"captionschanged",this.jI);this.l.K(b,"captionssettingschanged",this.rA);this.l.K(b,"videoplayerreset",this.xn);this.l.K(b,"mdxautoplaycancel",this.nC);this.O=this.l.K(b,"onVolumeChange",this.Ey);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.Py,this);c.subscribe("remotePlayerChange",this.Bk,this);c.subscribe("remoteQueueChange",this.xn,this);c.subscribe("autoplayUpNext",this.ry,
this);c.subscribe("previousNextChange",this.My,this);c.subscribe("nowAutoplaying",this.Iy,this);c.subscribe("autoplayDismissed",this.qy,this);this.suggestion=null;this.F=new g.pC(64);this.o=new g.K(this.pA,500,this);g.D(this,this.o);this.A=new g.K(this.qA,1E3,this);g.D(this,this.A);this.I=new i6(this.HM,0,this);g.D(this,this.I);this.C={};this.P=new g.K(this.QA,1E3,this);g.D(this,this.P);this.H=new g.Dl(this.GF,1E3,this);g.D(this,this.H);this.M=g.Ia;this.rA();this.xn();this.Bk()},n9=function(a,b){a.u.Jc(b,
a.i.getVideoData().lengthSeconds)},nra=function(a){n9(a,0);
a.o.stop();o9(a,new g.pC(64))},q9=function(a,b){if(p9(a)&&!a.D){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.ec(c,b));a.g.eA(a.i.getVideoData(1).videoId,c);a.C=A8(a.g).g}},r9=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Sa;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.Cf,B5(c));o9(a,new g.pC(1))},ora=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{yQ:1});
c&&c.length?(a.i.setOption("captions","track",b),a.D=!1):(a.i.loadModule("captions"),a.D=!0)}else a.i.setOption("captions","track",{})},p9=function(a){return A8(a.g).videoId==a.i.getVideoData(1).videoId},o9=function(a,b){a.A.stop();
var c=a.F;if(!g.vC(c,b)){var d=g.T(b,2);d!=g.T(a.F,2)&&g.jK(a.i,d);a.F=b;pra(a.u,c,b)}},s9=function(){g.V.call(this,{B:"div",
G:"ytp-mdx-popup-dialog",L:{role:"dialog"},J:[{B:"div",G:"ytp-mdx-popup-dialog-inner-content",J:[{B:"div",G:"ytp-mdx-popup-title",U:"You're signed out"},{B:"div",G:"ytp-mdx-popup-description",U:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{B:"div",G:"ytp-mdx-privacy-popup-buttons",J:[{B:"button",W:["ytp-button","ytp-mdx-privacy-popup-cancel"],U:"Cancel"},{B:"button",W:["ytp-button","ytp-mdx-privacy-popup-confirm"],
U:"Confirm"}]}]}]});this.l=new g.cQ(this,250);g.D(this,this.l);this.C=this.i["ytp-mdx-privacy-popup-cancel"];this.K(this.C,"click",this.o);this.u=this.i["ytp-mdx-privacy-popup-confirm"];this.K(this.u,"click",this.A)},t9=function(a){g.V.call(this,{B:"div",
G:"ytp-remote",J:[{B:"div",G:"ytp-remote-display-status",J:[{B:"div",G:"ytp-remote-display-status-icon",J:[g.sP()]},{B:"div",G:"ytp-remote-display-status-text",U:"{{statustext}}"}]}]});this.l=new g.cQ(this,250);g.D(this,this.l);this.o=a;this.K(a,"presentingplayerstatechange",this.u);qra(this,g.fK(a))},qra=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.T(b,128)?g.rN("Error on $RECEIVER_NAME",c):g.wC(b)||g.T(b,4)?g.rN("Playing on $RECEIVER_NAME",c):g.rN("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},u9=function(a,b){g.NT.call(this,"Play on",0,a,b);
this.l=a;this.F={};this.K(a,"onMdxReceiversChange",this.I);this.K(a,"presentingplayerstatechange",this.I);this.I()},v9=function(a){g.IK.call(this,a);
this.i={key:O5(),name:"This computer"};this.u=null;this.l=[];this.D=this.g=null;this.A=[this.i];this.o=this.i;this.jk=new g.pC(64);this.H=0;this.Km=-1;if(!g.Sy(g.W(this.player))){a=this.player;var b=g.jD(a);b&&(b=b.dn())&&(b=new u9(a,b),g.D(this,b));b=new t9(a);g.D(this,b);g.uK(a,b.element,4);this.F=new s9;g.D(this,this.F);g.uK(a,this.F.element,4);this.C=!!a9()}},pra=function(a,b,c){a.jk=c;
a.player.N("presentingplayerstatechange",new g.AD(c,b))},w9=function(a,b){b.key!=a.o.key&&(b.key==a.i.key?f9():(!g.P(g.W(a.player).experiments,"mdx_enable_privacy_disclosure")||wqa()||a.C||(g.wC(g.fK(a.player))||a.l.push(g.Up("statechange",function(c){!a.C&&g.CD(c,8)&&a.player.pauseVideo()},a)),a.player.pauseVideo(),a.F.l.show(),d9()||(k9=!0)),a.o=b,kra(b,rra(a))))},rra=function(a){var b=a.player.getPlaylistId(),c=a.player.getVideoData(1),d=c.videoId;
if(!b&&!d)return null;var e=a.player.getPlaylist();if(e){var f=[];for(var k=0;k<e.getLength();k++)f[k]=e.oa(k).videoId}else f=[d];e=a.player.getCurrentTime(1);a={videoIds:f,listId:b,videoId:d,playerParams:c.playerParams,clickTrackingParams:c.Cf,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==e?void 0:e};(c=B5(c))&&(a.locationInfo=c);return a},hqa=/^https?$/i,sra=["POST",
"PUT"];g.y(z5,g.Tf);g.h=z5.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.D+"; newUri="+a);b=b?b.toUpperCase():"GET";this.D=a;this.l="";this.u=0;this.aa=b;this.O=!1;this.i=!0;this.g=this.M?r5(this.M):r5(g.NY);this.P=this.M?this.M.getOptions():g.NY.getOptions();this.g.onreadystatechange=(0,g.x)(this.Tv,this);try{o5(s5(this,"Opening Xhr")),this.V=!0,this.g.open(b,String(a),!0),this.V=!1}catch(f){o5(s5(this,"Error opening Xhr: "+f.message));w5(this,f);return}a=c||
"";var e=this.headers.clone();d&&eqa(d,function(f,k){e.set(k,f)});
d=g.Xa(e.Gd(),fqa);c=g.v.FormData&&a instanceof g.v.FormData;!g.$a(sra,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.Z&&(this.g.responseType=this.Z);"withCredentials"in this.g&&this.g.withCredentials!==this.R&&(this.g.withCredentials=this.R);try{t5(this),0<this.A&&(this.I=gqa(this.g),o5(s5(this,"Will abort after "+this.A+"ms if incomplete, xhr2 "+this.I)),this.I?(this.g.timeout=this.A,this.g.ontimeout=(0,g.x)(this.Uv,this)):this.F=g.Hg(this.Uv,this.A,this)),o5(s5(this,"Sending request")),this.C=!0,this.g.send(a),this.C=!1}catch(f){o5(s5(this,"Send error: "+f.message)),w5(this,f)}};
g.h.Uv=function(){"undefined"!=typeof g.rY&&this.g&&(this.l="Timed out after "+this.A+"ms, aborting",this.u=8,s5(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&(s5(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.u=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),v5(this))};
g.h.T=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),v5(this,!0));z5.Xa.T.call(this)};
g.h.Tv=function(){this.ea()||(this.V||this.C||this.o?y5(this):this.nK())};
g.h.nK=function(){y5(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<x5(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.Ea(this.l)?this.l:String(this.l)};
var x6={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},w6={"'":"\\'"},tra={};g.h=F5.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.i.length};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.$a(this.g,a)||g.$a(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.Pma)(b,a);0<=c?(g.bb(b,c),b=!0):b=!1;return b||g.cb(this.i,a)};
g.h.xc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};
var pqa={AN:"atp",MP:"ska",BP:"que",aP:"mus",LP:"sus",rO:"dsp",IP:"seq"};H5.prototype.fg=function(){var a=new H5({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var a6,U5="",yqa=c6("loadCastFramework")||c6("loadCastApplicationFramework"),Rqa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.y(i6,g.B);g.h=i6.prototype;g.h.fD=function(a){this.o=arguments;this.g=!1;this.za?this.l=(0,g.G)()+this.Wc:this.za=g.Hg(this.u,this.Wc)};
g.h.stop=function(){this.za&&(g.v.clearTimeout(this.za),this.za=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.A.apply(null,this.o)))};
g.h.T=function(){this.stop();i6.Xa.T.call(this)};
g.h.gD=function(){this.l?(this.za=g.Hg(this.u,this.l-(0,g.G)()),this.l=null):(this.za=null,this.i?this.g=!0:(this.g=!1,this.A.apply(null,this.o)))};j6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
j6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};g.h=k6.prototype;g.h.Zg=null;g.h.we=!1;g.h.Wi=null;g.h.Rs=null;g.h.Fi=null;g.h.Vh=null;g.h.Wf=null;g.h.Dg=null;g.h.sh=null;g.h.qc=null;g.h.bl=0;g.h.Be=null;g.h.lo=null;g.h.pg=null;g.h.Rj=-1;g.h.Rz=!0;g.h.Og=!1;g.h.Pp=0;g.h.Gn=null;var r6={},p6={};g.h=k6.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.UL=function(a){a=a.target;var b=this.Gn;b&&3==x5(a)?b.Nj():this.YA(a)};
g.h.YA=function(a){try{if(a==this.qc)a:{var b=x5(this.qc),c=this.qc.u,d=this.qc.getStatus();if(g.Ld&&!g.od(10)||g.Nd&&!g.nd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Dh&&!A5(this.qc))break a;this.Og||4!=b||7==c||(8==c||0>=d?this.g.se(3):this.g.se(2));B6(this);var e=this.qc.getStatus();this.Rj=e;var f=A5(this.qc);(this.we=200==e)?(4==b&&t6(this),this.u?(v6(this,b,f),g.Dh&&this.we&&3==b&&(this.ba.ca(this.i,"tick",this.OL),this.i.start())):s6(this,f),this.we&&!this.Og&&(4==b?this.g.un(this):(this.we=
!1,o6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.pg=3,q6(13)):(this.pg=0,q6(14)),t6(this),u6(this))}}catch(k){this.qc&&A5(this.qc)}finally{}};
g.h.OL=function(){var a=x5(this.qc),b=A5(this.qc);this.bl<b.length&&(B6(this),v6(this,a,b),this.we&&4!=a&&o6(this))};
g.h.nL=function(a){A6((0,g.x)(this.mL,this,a),0)};
g.h.mL=function(a){this.Og||(B6(this),s6(this,a),o6(this))};
g.h.Wy=function(a){A6((0,g.x)(this.lL,this,a),0)};
g.h.lL=function(a){this.Og||(t6(this),this.we=a,this.g.un(this),this.g.se(4))};
g.h.cancel=function(){this.Og=!0;t6(this)};
g.h.xL=function(){this.Wi=null;var a=(0,g.G)();0<=a-this.Rs?(2!=this.Vh&&this.g.se(3),t6(this),this.pg=2,q6(18),u6(this)):z6(this,this.Rs-a)};
g.h.getLastError=function(){return this.pg};g.h=F6.prototype;g.h.Mp=null;g.h.Bd=null;g.h.Hn=!1;g.h.Sv=null;g.h.Zl=null;g.h.zq=null;g.h.Op=null;g.h.ce=null;g.h.yf=-1;g.h.Qj=null;g.h.ij=null;g.h.connect=function(a){this.Op=a;a=G6(this.g,null,this.Op);q6(3);this.Sv=(0,g.G)();var b=this.g.D;null!=b?(this.Qj=b[0],(this.ij=b[1])?(this.ce=1,H6(this)):(this.ce=2,J6(this))):(q5(a,"MODE","init"),this.Bd=new k6(this,void 0,void 0,void 0),this.Bd.Zg=this.Mp,n6(this.Bd,a,!1,null,!0),this.ce=0)};
g.h.oC=function(a){if(a)this.ce=2,J6(this);else{q6(4);var b=this.g;b.Je=b.eg.yf;c7(b,9)}a&&this.se(2)};
g.h.lp=function(a){return this.g.lp(a)};
g.h.abort=function(){this.Bd&&(this.Bd.cancel(),this.Bd=null);this.yf=-1};
g.h.Rv=function(){return!1};
g.h.Qy=function(a,b){this.yf=a.Rj;if(0==this.ce)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.Je=this.yf;c7(c,2);return}this.Qj=c[0];this.ij=c[1]}else c=this.g,c.Je=this.yf,c7(c,2);else if(2==this.ce)if(this.Hn)q6(7),this.zq=(0,g.G)();else if("11111"==b){if(q6(6),this.Hn=!0,this.Zl=(0,g.G)(),c=this.Zl-this.Sv,!g.Ld||g.od(10)||500>c)this.yf=200,this.Bd.cancel(),q6(12),I6(this.g,this,!0)}else q6(8),this.Zl=this.zq=(0,g.G)(),this.Hn=!1};
g.h.un=function(){this.yf=this.Bd.Rj;if(this.Bd.we)0==this.ce?this.ij?(this.ce=1,H6(this)):(this.ce=2,J6(this)):2==this.ce&&((!g.Ld||g.od(10)?!this.Hn:200>this.zq-this.Zl)?(q6(11),I6(this.g,this,!1)):(q6(12),I6(this.g,this,!0)));else{0==this.ce?q6(9):2==this.ce&&q6(10);var a=this.g;this.Bd.getLastError();a.Je=this.yf;c7(a,2)}};
g.h.Pk=function(){return this.g.Pk()};
g.h.isActive=function(){return this.g.isActive()};
g.h.se=function(a){this.g.se(a)};g.h=K6.prototype;g.h.xj=null;g.h.xd=null;g.h.Sb=null;g.h.Lp=null;g.h.fm=null;g.h.ju=null;g.h.rm=null;g.h.wk=0;g.h.DH=0;g.h.Tc=null;g.h.lg=null;g.h.nf=null;g.h.Tg=null;g.h.eg=null;g.h.jo=null;g.h.ii=-1;g.h.Dw=-1;g.h.Je=-1;g.h.Ph=0;g.h.Ih=0;g.h.Pg=8;var d7=new g.Tf;g.y(L6,g.tf);g.y(M6,g.tf);g.y(N6,g.tf);g.h=K6.prototype;g.h.connect=function(a,b,c,d,e){q6(0);this.Lp=b;this.xj=c||{};d&&g.Da(e)&&(this.xj.OSID=d,this.xj.OAID=e);this.A?(A6((0,g.x)(this.Du,this,a),100),T6(this)):this.Du(a)};
g.h.Du=function(a){this.eg=new F6(this);this.eg.Mp=null;this.eg.i=this.u;this.eg.connect(a)};
g.h.Rv=function(){return 0==this.g};
g.h.Vy=function(a){this.lg=null;Y6(this,a)};
g.h.Uy=function(){this.nf=null;this.Sb=new k6(this,this.l,"rpc",this.C);this.Sb.Zg=null;this.Sb.Pp=0;var a=this.ju.clone();g.Ym(a,"RID","rpc");g.Ym(a,"SID",this.l);g.Ym(a,"CI",this.jo?"0":"1");g.Ym(a,"AID",this.ii);P6(this,a);if(!g.Ld||g.od(10))g.Ym(a,"TYPE","xmlhttp"),n6(this.Sb,a,!0,this.rm,!1);else{g.Ym(a,"TYPE","html");var b=this.Sb,c=!!this.rm;b.Vh=3;b.Wf=p5(a.clone());y6(b,c)}};
g.h.Qy=function(a,b){if(0!=this.g&&(this.Sb==a||this.xd==a))if(this.Je=a.Rj,this.xd==a&&3==this.g)if(7<this.Pg){try{var c=this.u.parse(b)}catch(f){c=null}if(g.La(c)&&3==c.length)if(0==c[0])a:{if(!this.nf){if(this.Sb)if(this.Sb.Fi+3E3<this.xd.Fi)U6(this),this.Sb.cancel(),this.Sb=null;else break a;a7(this);q6(19)}}else this.Dw=c[1],0<this.Dw-this.ii&&37500>c[2]&&this.jo&&0==this.Ih&&!this.Tg&&(this.Tg=A6((0,g.x)(this.fI,this),6E3));else c7(this,11)}else b!=tra.WN.g&&c7(this,11);else if(this.Sb==a&&
U6(this),!g.wb(b)){c=this.u.parse(b);g.La(c);for(var d=0;d<c.length;d++){var e=c[d];this.ii=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.rm=e[2],e=e[3],null!=e?this.Pg=e:this.Pg=6,this.g=3,this.Tc&&this.Tc.xu(),this.ju=G6(this,this.Pk()?this.rm:null,this.Lp),Z6(this)):"stop"==e[0]&&c7(this,7):3==this.g&&("stop"==e[0]?c7(this,7):"noop"!=e[0]&&this.Tc&&this.Tc.wu(e),this.Ih=0)}}};
g.h.fI=function(){null!=this.Tg&&(this.Tg=null,this.Sb.cancel(),this.Sb=null,a7(this),q6(20))};
g.h.un=function(a){if(this.Sb==a){U6(this);this.Sb=null;var b=2}else if(this.xd==a)this.xd=null,b=1;else return;this.Je=a.Rj;if(0!=this.g)if(a.we)1==b?(b=(0,g.G)()-a.Fi,d7.dispatchEvent(new M6(d7,a.sh?a.sh.length:0,b,this.Ph)),S6(this),this.o.length=0):Z6(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Je)){if(d=1==b)this.xd||this.lg||1==this.g||2<=this.Ph?d=!1:(this.lg=A6((0,g.x)(this.Vy,this,a),$6(this,this.Ph)),this.Ph++,d=!0);d=!(d||2==b&&a7(this))}if(d)switch(c){case 1:c7(this,
5);break;case 4:c7(this,10);break;case 3:c7(this,6);break;case 7:c7(this,12);break;default:c7(this,2)}}};
g.h.FC=function(a){if(!g.$a(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.yM=function(a){a?q6(2):(q6(1),b7(this,8))};
g.h.lp=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new z5;a.R=!1;return a};
g.h.isActive=function(){return!!this.Tc&&this.Tc.isActive(this)};
g.h.se=function(a){d7.dispatchEvent(new N6(d7,a))};
g.h.Pk=function(){return!(!g.Ld||g.od(10))};
g.h=e7.prototype;g.h.xu=function(){};
g.h.wu=function(){};
g.h.vu=function(){};
g.h.Yo=function(){};
g.h.tv=function(){return{}};
g.h.isActive=function(){return!0};g.y(f7,g.B);g.h=f7.prototype;g.h.fL=function(){this.Wc=Math.min(3E5,2*this.Wc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Wc+15E3*Math.random();g.fo(this.g,a);this.i=(0,g.G)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Wc=5E3};g.y(g7,e7);g.h=g7.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.If=function(a){return this.l.ah(a)};
g.h.N=function(a,b){return this.l.N.apply(this.l,arguments)};
g.h.dispose=function(){this.fb||(this.fb=!0,g.rf(this.l),h7(this),g.rf(this.i),this.i=null)};
g.h.ea=function(){return this.fb};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.F="";this.i.stop();this.u=a||null;this.o=b||0;a=this.H+"/test";b=this.H+"/bind";var d=new K6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.I),e=this.g;e&&(e.Tc=null);d.Tc=this;this.g=d;e?this.g.connect(a,b,this.A,e.l,e.ii):c?this.g.connect(a,b,this.A,c.sessionId,c.arrayId):this.g.connect(a,b,this.A)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.ec(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.C.push(c):i7(this)&&V6(this.g,c)};
g.h.xu=function(){this.i.reset();this.u=null;this.o=0;if(this.C.length){var a=this.C;this.C=[];for(var b=0,c=a.length;b<c;++b)V6(this.g,a[b])}this.N("handlerOpened")};
g.h.vu=function(a){var b=2==a&&401==this.g.Je;4==a||b||this.i.start();this.N("handlerError",a)};
g.h.Yo=function(a){if(!this.i.isActive())this.N("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.C.push(d)}};
g.h.tv=function(){var a={v:2};this.F&&(a.gsessionid=this.F);0!=this.o&&(a.ui=""+this.o);0!=this.D&&(a.ui=""+this.D);this.u&&g.ec(a,this.u);return a};
g.h.wu=function(a){"S"==a[0]?this.F=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),R6(this.g)):this.N("handlerMessage",new Cqa(a[0],a[1]))};
g.h.dM=function(){this.i.isActive();var a=this.g,b=0;a.Sb&&b++;a.xd&&b++;0==b&&this.connect(this.u,this.o)};j7.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
j7.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
j7.prototype.u=function(a){a(Error("request timed out"))};var Iqa=(0,g.G)(),o7=null,s7=Array(50),r7=-1,t7=!1;g.y(u7,g.O);u7.prototype.Hd=function(){return this.g};
u7.prototype.contains=function(a){return!!P5(this.g,a)};
u7.prototype.get=function(a){return a?Q5(this.g,a):null};
u7.prototype.info=function(a){q7(this.C,a)};g.t(w7,g.O);g.h=w7.prototype;g.h.start=function(){!this.g&&isNaN(this.za)&&this.bB()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.za)||(g.Np(this.za),this.za=NaN)};
g.h.T=function(){this.stop();g.O.prototype.T.call(this)};
g.h.bB=function(){this.za=NaN;this.g=g.Iq(k7(this.A,"/pairing/get_screen"),{method:"POST",ub:{pairing_code:this.u},timeout:5E3,onSuccess:(0,g.x)(this.aN,this),onError:(0,g.x)(this.ZM,this),he:(0,g.x)(this.bN,this)})};
g.h.aN=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.N("pairingComplete",new I5(c))};
g.h.ZM=function(a){this.g=null;a.status&&404==a.status?this.i>=ura.length?this.N("pairingFailed",Error("DIAL polling timed out")):(a=ura[this.i],this.za=g.Lp((0,g.x)(this.bB,this),a),this.i++):this.N("pairingFailed",Error("Server error "+a.status))};
g.h.bN=function(){this.g=null;this.N("pairingFailed",Error("Server not responding"))};
var ura=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.y(y7,u7);g.h=y7.prototype;g.h.start=function(){x7(this)&&this.N("screenChange");!g.kt("yt-remote-lounge-token-expiration")&&z7(this);g.Np(this.i);this.i=g.Lp((0,g.x)(this.start,this),1E4)};
g.h.add=function(a,b){x7(this);v7(this,a);A7(this,!1);this.N("screenChange");b(a);a.token||z7(this)};
g.h.remove=function(a,b){var c=x7(this);Kqa(this,a)&&(A7(this,!1),c=!0);b(a);c&&this.N("screenChange")};
g.h.co=function(a,b,c,d){var e=x7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,A7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.N("screenChange")};
g.h.T=function(){g.Np(this.i);y7.Xa.T.call(this)};
g.h.qD=function(a){x7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}A7(this,!b);b&&q7(this.C,"Missed "+b+" lounge tokens.")};
g.h.pD=function(a){q7(this.C,"Requesting lounge tokens failed: "+a)};g.t(C7,g.O);g.h=C7.prototype;g.h.start=function(){var a=parseInt(g.kt("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.G)()-144E5<a?0:a)?F7(this):(this.o=(0,g.G)()+3E5,g.jt("yt-remote-fast-check-period",this.o),this.Tr())};
g.h.isEmpty=function(){return g.Xb(this.g)};
g.h.update=function(){B7("Updating availability on schedule.");var a=this.A(),b=g.Lb(this.g,function(c,d){return c&&!!Q5(a,d)},this);
E7(this,b)};
g.h.T=function(){g.Np(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);g.O.prototype.T.call(this)};
g.h.Tr=function(){g.Np(this.l);this.l=NaN;this.i&&this.i.abort();var a=G7(this);if(C5(a)){var b=k7(this.u,"/pairing/get_screen_availability");this.i=l7(this.u,b,{lounge_token:g.Rb(a).join(",")},(0,g.x)(this.JK,this,a),(0,g.x)(this.IK,this))}else E7(this,{}),F7(this)};
g.h.JK=function(a,b){this.i=null;var c=g.Rb(G7(this));if(g.rb(c,g.Rb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;E7(this,d);F7(this)}else this.Hb("Changing Screen set during request."),this.Tr()};
g.h.IK=function(a){this.Hb("Screen availability failed: "+a);this.i=null;F7(this)};
g.h.Hb=function(a){q7("OnlineScreenService",a)};g.y(H7,u7);g.h=H7.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.N("screenChange"),this.i.isEmpty()||this.N("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.co=function(a,b,c,d){this.l.contains(a)?this.l.co(a,b,c,d):(a="Updating name of unknown screen: "+a.name,q7(this.C,a),d(Error(a)))};
g.h.Hd=function(a){return a?this.g:g.eb(this.g,(0,g.Xd)(this.o,function(b){return!this.contains(b)},this))};
g.h.cB=function(){return(0,g.Xd)(this.Hd(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.dB=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new w7(this.A,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(k){g.rf(f);d(I7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.rf(f);e(k)});
f.start();return(0,g.x)(f.stop,f)};
g.h.dN=function(a,b,c,d){g.Iq(k7(this.A,"/pairing/get_screen"),{method:"POST",ub:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var k=new I5(f.screen||{});if(!k.name||K7(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);K7(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(I7(this,k))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
he:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.T=function(){g.rf(this.l);g.rf(this.i);H7.Xa.T.call(this)};
g.h.yD=function(){L7(this);this.N("screenChange");this.i.update()};
H7.prototype.dispose=H7.prototype.dispose;g.y(N7,g.O);g.h=N7.prototype;g.h.wn=function(a){this.l=a;this.N("sessionScreen",this.l)};
g.h.Ld=function(a){this.ea()||(a&&O7(this,""+a),this.l=null,this.N("sessionScreen",null))};
g.h.info=function(a){q7(this.P,a)};
g.h.fB=function(){return null};
g.h.hs=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){O7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.T=function(){this.hs("");N7.Xa.T.call(this)};g.y(Q7,N7);g.h=Q7.prototype;g.h.gs=function(a){if(this.g){if(this.g==a)return;O7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.A);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u)}this.g=a;this.g.addUpdateListener(this.A);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.u);Oqa(this)};
g.h.ki=function(a){this.info("launchWithParams no-op for Cast: "+g.Lg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.x)(function(){this.Ld()},this),(0,g.x)(function(){this.Ld(Error("Failed to stop receiver app."))},this)):this.Ld(Error("Stopping cast device witout session."))};
g.h.hs=g.Ia;g.h.T=function(){this.info("disposeInternal");g.Np(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.A),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u));this.g=null;Q7.Xa.T.call(this)};
g.h.IL=function(a,b){if(!this.ea())if(b){var c=E5(b);if(g.Oa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Lg(c));switch(d){case "mdxSessionStatus":P7(this,c.screenId);break;default:O7(this,"Unknown youtube message: "+d)}}else O7(this,"Unable to parse message.")}else O7(this,"No data in message.")};
g.h.Jv=function(a,b,c,d){J7(this.F,this.i.label,a,this.i.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(O7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Lp((0,g.x)(this.Jv,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.fB=function(){return this.g};
g.h.eN=function(a){this.ea()||a||(O7(this,"Cast session died."),this.Ld())};g.y(R7,N7);g.h=R7.prototype;g.h.gs=function(a){this.o=a;this.o.addUpdateListener(this.I)};
g.h.ki=function(a){this.u=a;this.C()};
g.h.stop=function(){this.g();this.g=g.Ia;g.Np(this.A);this.o?this.o.stop((0,g.x)(this.Ld,this,null),(0,g.x)(this.Ld,this,"Failed to stop DIAL device.")):this.Ld()};
g.h.T=function(){this.g();this.g=g.Ia;g.Np(this.A);this.o&&this.o.removeUpdateListener(this.I);this.o=null;R7.Xa.T.call(this)};
g.h.hN=function(a){this.ea()||a||(O7(this,"DIAL session died."),this.g(),this.g=g.Ia,this.Ld())};
g.h.cq=function(a){this.H=O5();if(this.u){var b=new chrome.cast.DialLaunchResponse(!0,T7(this));a(b);S7(this)}else this.C=(0,g.x)(function(){g.Np(this.A);this.C=g.Ia;this.A=NaN;var c=new chrome.cast.DialLaunchResponse(!0,T7(this));a(c);S7(this)},this),this.A=g.Lp((0,g.x)(function(){this.C()},this),100)};
g.h.TD=function(a,b,c){J7(this.F,this.D.receiver.label,a,this.i.friendlyName,(0,g.x)(function(d){d&&d.token?(this.wn(d),b(new chrome.cast.DialLaunchResponse(!1))):this.cq(b,c)},this),(0,g.x)(function(d){O7(this,"Failed to get DIAL screen: "+d);
this.cq(b,c)},this))};g.y(U7,N7);U7.prototype.stop=function(){this.Ld()};
U7.prototype.gs=g.Ia;U7.prototype.ki=function(){g.Np(this.g);this.g=NaN;var a=Q5(this.F.Hd(),this.i.label);a?this.wn(a):this.Ld(Error("No such screen"))};
U7.prototype.T=function(){g.Np(this.g);this.g=NaN;U7.Xa.T.call(this)};g.y(V7,g.O);g.h=V7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.C);this.D||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.sK,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.Sy,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.GI,this);chrome.cast.initialize(c,(0,g.x)(function(){this.ea()||
(chrome.cast.addReceiverActionListener(this.o),Fqa(),this.i.subscribe("onlineScreenChange",(0,g.x)(this.eB,this)),this.l=$7(this),chrome.cast.setCustomReceivers(this.l,g.Ia,(0,g.x)(function(k){this.Hb("Failed to set initial custom receivers: "+g.Lg(k))},this)),this.N("yt-remote-cast2-availability-change",Y7(this)),b(!0))},this),(0,g.x)(function(k){this.Hb("Failed to initialize API: "+g.Lg(k));
b(!1)},this))};
g.h.mM=function(a,b){X7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)X7("Unsetting old screen status: "+this.g.i.friendlyName),Z7(this,null)}if(a&&b){if(!this.g){c=Q5(this.i.Hd(),a);if(!c){X7("setConnectedScreenStatus: Unknown screen.");return}var d=W7(this,c);d||(X7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ia,(0,g.x)(function(e){this.Hb("Failed to set initial custom receivers: "+g.Lg(e))},this)));
X7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);Z7(this,new U7(this.i,d),!0)}this.g.hs(b)}else X7("setConnectedScreenStatus: no screen.")};
g.h.nM=function(a){this.ea()?this.Hb("Setting connection data on disposed cast v2"):this.g?this.g.ki(a):this.Hb("Setting connection data without a session")};
g.h.gN=function(){this.ea()?this.Hb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),Z7(this,null)):X7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.Sy,this),(0,g.x)(this.OK,this))};
g.h.T=function(){this.i.unsubscribe("onlineScreenChange",(0,g.x)(this.eB,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.cb(g.w("yt.mdx.remote.debug.handlers_")||[],m7);g.rf(this.g);V7.Xa.T.call(this)};
g.h.Hb=function(a){q7("Controller",a)};
g.h.Ty=function(a,b){this.g==a&&(b||Z7(this,null),this.N("yt-remote-cast2-session-change",b))};
g.h.oK=function(a,b){if(!this.ea())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),X7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)X7("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{X7("onReceiverAction_: Casting to active receiver.");this.g.l&&this.N("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:Z7(this,
new U7(this.i,a));break;case chrome.cast.ReceiverType.DIAL:Z7(this,new R7(this.i,a,this.A));break;case chrome.cast.ReceiverType.CAST:Z7(this,new Q7(this.i,a));break;default:this.Hb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Hb("Stopping receiver w/o session: "+a.friendlyName)}else this.Hb("onReceiverAction_ called without receiver.")};
g.h.GI=function(a){if(this.ea())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Hb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Hb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return X7("Reselecting dial screen."),
this.N("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Hb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);Z7(this,new R7(this.i,b,this.A))}b=this.g;b.D=a;return b.D.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.TD,b,(b.D.extraData||{}).screenId||null)):new Promise((0,g.x)(b.cq,b))};
g.h.Sy=function(a){if(!this.ea()){X7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)X7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),Z7(this,new Q7(this.i,b),!0);else{this.Hb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=Q5(this.i.Hd(),c.label);d&&J5(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(X7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.rf(this.g),this.g=new Q7(this.i,b),this.g.subscribe("sessionScreen",(0,g.x)(this.Ty,this,this.g)),this.g.ki(null));this.g.gs(a)}}};
g.h.fN=function(){return this.g?this.g.fB():null};
g.h.OK=function(a){this.ea()||(this.Hb("Failed to estabilish a session: "+g.Lg(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&Z7(this,null))};
g.h.sK=function(a){X7("Receiver availability updated: "+a);if(!this.ea()){var b=Y7(this);this.u=a==chrome.cast.ReceiverAvailability.AVAILABLE;Y7(this)!=b&&this.N("yt-remote-cast2-availability-change",Y7(this))}};
g.h.eB=function(){this.ea()||(this.l=$7(this),X7("Updating custom receivers: "+g.Lg(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ia,(0,g.x)(function(){this.Hb("Failed to set custom receivers.")},this)),this.N("yt-remote-cast2-availability-change",Y7(this)))};
V7.prototype.setLaunchParams=V7.prototype.nM;V7.prototype.setConnectedScreenStatus=V7.prototype.mM;V7.prototype.stopSession=V7.prototype.gN;V7.prototype.getCastSession=V7.prototype.fN;V7.prototype.requestSession=V7.prototype.requestSession;V7.prototype.init=V7.prototype.init;V7.prototype.dispose=V7.prototype.dispose;var i8=[];q8.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";r8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Ke=a.hasPrevious,this.hasNext=a.hasNext,this.C=a.playerTime,this.A=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.F=a.loadedTime,this.l=a.liveIngestionTime,this.u=
!isNaN(this.l))};
q8.prototype.isAdPlaying=function(){return 1081==this.playerState};
q8.prototype.getDuration=function(){return this.u?this.D+s8(this):this.D};
q8.prototype.clone=function(){return new q8(w8(this))};g.t(z8,g.O);g.h=z8.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ia,H8(this,"play")):F8(this,"play"),E8(this,1,u8(A8(this))),this.N("remotePlayerChange")):C8(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ia,H8(this,"pause")):F8(this,"pause"),E8(this,2,u8(A8(this))),this.N("remotePlayerChange")):C8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=A8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ia,H8(this,"seekTo",{newTime:a}))}else F8(this,"seekTo",{newTime:a});E8(this,3,a);this.N("remotePlayerChange")}else C8(this,g.Ra(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ia,H8(this,"stopVideo")):F8(this,"stopVideo");var a=A8(this);a.index=-1;a.videoId="";r8(a);D8(this,a);this.N("remotePlayerChange")}else C8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=A8(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.x)(function(){q7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.Hb("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.x)(function(){q7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.Hb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);F8(this,"setVolume",e)}c.muted=b;c.volume=a;D8(this,c)}else C8(this,g.Ra(this.setVolume,a,b))};
g.h.eA=function(a,b){if(1==this.g){var c=A8(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Lg(b.style),g.ec(d,c.g));F8(this,"setSubtitlesTrack",d);D8(this,c)}else C8(this,g.Ra(this.eA,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();F8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=A8(this);d.audioTrackId=c;D8(this,d)}else C8(this,g.Ra(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=A8(this);c=c||0;var m={videoId:a,currentIndex:c};v8(l,a,c);g.Da(b)&&(t8(l,b),m.currentTime=b);g.Da(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Lg(k));F8(this,"setPlaylist",m);d||D8(this,l)};
g.h.Cn=function(a,b){if(1==this.g){if(a&&b){var c=A8(this);v8(c,a,b);D8(this,c)}F8(this,"previous")}else C8(this,g.Ra(this.Cn,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=A8(this);v8(c,a,b);D8(this,c)}F8(this,"next")}else C8(this,g.Ra(this.nextVideo,a,b))};
g.h.Uu=function(){1==this.g?F8(this,"dismissAutoplay"):C8(this,this.Uu)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.N("proxyStateChange",a,this.g)}g.O.prototype.dispose.call(this)};
g.h.T=function(){B8(this);this.o=null;this.u.clear();y8(this,null);g.O.prototype.T.call(this)};
g.h.Us=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.N("proxyStateChange",b,a);if(1==a)for(;!this.u.isEmpty();)b=a=this.u,0==b.g.length&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.lK=function(a,b){this.N(a,b)};
g.h.lI=function(a){if(!a)this.zk(null),y8(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=A8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)q7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,D8(this,b)}};
g.h.zk=function(a){q7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.D);if(this.i=a)this.i.addUpdateListener(this.D),G8(this),this.N("remotePlayerChange")};
g.h.kI=function(a){a?(G8(this),this.N("remotePlayerChange")):this.zk(null)};
g.h.Fs=function(){F8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.yI=function(){var a=m8();a&&y8(this,a)};
g.h.Hb=function(a){q7("CP",a)};g.t(I8,g.O);g.h=I8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Da(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Da(k)&&(l.currentIndex=k);c&&(this.Oa.listId=c);this.Oa.videoId=d;this.Oa.index=k||0;this.Oa.state=3;t8(this.Oa,m);this.o="UNSUPPORTED";J8("Connecting with setPlaylist and params: "+g.Lg(l));this.g.connect({method:"setPlaylist",
params:g.Lg(l)},a,X5())}else J8("Connecting without params"),this.g.connect({},a,X5());Vqa(this)};
g.h.dispose=function(){this.ea()||(this.N("beforeDispose"),K8(this,3));g.O.prototype.dispose.call(this)};
g.h.T=function(){L8(this);N8(this);M8(this);g.Np(this.C);this.C=NaN;g.Np(this.D);this.D=NaN;this.l=null;g.Sr(this.P);this.P.length=0;this.g.dispose();g.O.prototype.T.call(this);this.o=this.A=this.i=this.Oa=this.g=null};
g.h.jD=function(){this.Mh(2)};
g.h.pI=function(){J8("Channel opened");this.I&&(this.I=!1,M8(this),this.H=g.Lp((0,g.x)(function(){J8("Timing out waiting for a screen.");this.Mh(1)},this),15E3));
vqa(Dqa(this.g),this.M)};
g.h.mI=function(){J8("Channel closed");isNaN(this.u)?$5(!0):$5();this.dispose()};
g.h.nI=function(a){$5();isNaN(this.Fj())?(J8("Channel error: "+a+" without reconnection"),this.dispose()):(this.I=!0,J8("Channel error: "+a+" with reconnection in "+this.Fj()+" ms"),K8(this,2))};
g.h.oI=function(a){a.params?J8("Received: action="+a.action+", params="+g.Lg(a.params)):J8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=E5(a.params.devices);this.i=(0,g.ge)(a,function(c){return new H5(c)});
a=!!g.Xa(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
Q8(this,a);break;case "loungeScreenDisconnected":g.db(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
Q8(this,!1);break;case "remoteConnected":var b=new H5(E5(a.params.device));g.Xa(this.i,function(c){return b?c.id==b.id:!1})||kqa(this.i,b);
break;case "remoteDisconnected":b=new H5(E5(a.params.device));g.db(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":R8(this,a);break;case "nowPlaying":Yqa(this,a);break;case "onStateChange":S8(this,a);break;case "onAdStateChange":Zqa(this,a);break;case "onVolumeChanged":$qa(this,a);break;case "onSubtitlesTrackChanged":Xqa(this,a);break;case "nowAutoplaying":ara(this,a);break;case "autoplayDismissed":this.N("autoplayDismissed");break;case "autoplayUpNext":this.A=a.params.videoId||null;this.N("autoplayUpNext",this.A);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.N("autoplayModeChange",this.o);"DISABLED"==this.o&&this.N("autoplayDismissed");break;case "onHasPreviousNextChanged":bra(this,a);break;case "requestAssistedSignIn":this.N("assistedSignInRequested",a.params.authCode);break;default:J8("Unrecognized action: "+a.action)}};
g.h.aM=function(){if(this.l){var a=this.l;this.l=null;this.Oa.videoId!=a&&O8(this,"getNowPlaying")}};
g.h.ZC=function(){var a=3;this.ea()||(a=0,isNaN(this.Fj())?i7(this.g)&&isNaN(this.u)&&(a=1):a=2);return a};
g.h.Mh=function(a){J8("Disconnecting with "+a);L8(this);this.N("beforeDisconnect",a);1==a&&$5();h7(this.g,a);this.dispose()};
g.h.YC=function(){var a=this.Oa;this.l&&(a=this.Oa.clone(),v8(a,this.l,a.index));return w8(a)};
g.h.oM=function(a){var b=new q8(a);b.videoId&&b.videoId!=this.Oa.videoId&&(this.l=b.videoId,g.Np(this.C),this.C=g.Lp((0,g.x)(this.aM,this),5E3));var c=[];this.Oa.listId==b.listId&&this.Oa.videoId==b.videoId&&this.Oa.index==b.index||c.push("remoteQueueChange");this.Oa.playerState==b.playerState&&this.Oa.volume==b.volume&&this.Oa.muted==b.muted&&u8(this.Oa)==u8(b)&&g.Lg(this.Oa.g)==g.Lg(b.g)||c.push("remotePlayerChange");this.Oa.reset(a);(0,g.A)(c,function(d){this.N(d)},this)};
g.h.Gv=function(){var a=this.g.A.id,b=g.Xa(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.Fj=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.G)():NaN};
g.h.RC=function(){return this.o||"UNSUPPORTED"};
g.h.SC=function(){return this.A||""};
g.h.YM=function(){if(!isNaN(this.Fj())){var a=this.g.i;g.go(a.g);a.start()}};
g.h.hM=function(a,b){O8(this,a,b);P8(this)};
I8.prototype.subscribe=I8.prototype.subscribe;I8.prototype.unsubscribeByKey=I8.prototype.If;I8.prototype.getProxyState=I8.prototype.ZC;I8.prototype.disconnect=I8.prototype.Mh;I8.prototype.getPlayerContextData=I8.prototype.YC;I8.prototype.setPlayerContextData=I8.prototype.oM;I8.prototype.getOtherConnectedRemoteId=I8.prototype.Gv;I8.prototype.getReconnectTimeout=I8.prototype.Fj;I8.prototype.getAutoplayMode=I8.prototype.RC;I8.prototype.getAutoplayVideoId=I8.prototype.SC;I8.prototype.reconnect=I8.prototype.YM;
I8.prototype.sendMessage=I8.prototype.hM;g.t(T8,u7);g.h=T8.prototype;g.h.Hd=function(a){return this.Vc.$_gs(a)};
g.h.contains=function(a){return!!this.Vc.$_c(a)};
g.h.get=function(a){return this.Vc.$_g(a)};
g.h.start=function(){this.Vc.$_st()};
g.h.add=function(a,b,c){this.Vc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Vc.$_r(a,b,c)};
g.h.co=function(a,b,c,d){this.Vc.$_un(a,b,c,d)};
g.h.T=function(){for(var a=0,b=this.i.length;a<b;++a)this.Vc.$_ubk(this.i[a]);this.i.length=0;this.Vc=null;u7.prototype.T.call(this)};
g.h.cN=function(){this.N("screenChange")};
g.h.QJ=function(){this.N("onlineScreenChange")};
H7.prototype.$_st=H7.prototype.start;H7.prototype.$_gspc=H7.prototype.dN;H7.prototype.$_gsppc=H7.prototype.dB;H7.prototype.$_c=H7.prototype.contains;H7.prototype.$_g=H7.prototype.get;H7.prototype.$_a=H7.prototype.add;H7.prototype.$_un=H7.prototype.co;H7.prototype.$_r=H7.prototype.remove;H7.prototype.$_gs=H7.prototype.Hd;H7.prototype.$_gos=H7.prototype.cB;H7.prototype.$_s=H7.prototype.subscribe;H7.prototype.$_ubk=H7.prototype.If;var l9=null,k9=!1,U8=null,V8=null,j9=null,Z8=[];g.t(m9,g.B);g.h=m9.prototype;
g.h.T=function(){g.B.prototype.T.call(this);this.o.stop();this.A.stop();this.I.stop();this.M();this.g.unsubscribe("proxyStateChange",this.Py,this);this.g.unsubscribe("remotePlayerChange",this.Bk,this);this.g.unsubscribe("remoteQueueChange",this.xn,this);this.g.unsubscribe("autoplayUpNext",this.ry,this);this.g.unsubscribe("previousNextChange",this.My,this);this.g.unsubscribe("nowAutoplaying",this.Iy,this);this.g.unsubscribe("autoplayDismissed",this.qy,this);this.g=this.u=null};
g.h.mx=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(p9(this)){if(!A8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==A8(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.H.Nj(c[0],c[1]);break;case "control_subtitles_set_track":q9(this,c[0]);break;case "control_set_audio_track":c=c[0],p9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();r9(this,0==c?void 0:c);break;case "control_seek":r9(this,c[0]);break;case "control_subtitles_set_track":q9(this,c[0]);break;case "control_set_audio_track":c=c[0],p9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.jI=function(a){this.I.fD(a)};
g.h.HM=function(a){this.mx("control_subtitles_set_track",g.Xb(a)?null:a)};
g.h.rA=function(){var a=this.i.getOption("captions","track");g.Xb(a)||q9(this,a)};
g.h.Ey=function(a){if(p9(this)){this.g.unsubscribe("remotePlayerChange",this.Bk,this);var b=Math.round(a.volume);a=!!a.muted;var c=A8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.P.start();this.g.subscribe("remotePlayerChange",this.Bk,this)}};
g.h.kJ=function(){g.Xb(this.C)||ora(this,this.C);this.D=!1};
g.h.Py=function(a,b){this.A.stop();2==b&&this.qA()};
g.h.Bk=function(){if(p9(this)){this.o.stop();var a=A8(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.Km=1;break;case 1082:case 1083:this.u.Km=0;break;default:this.u.Km=-1}switch(a.playerState){case 1081:case 1:o9(this,new g.pC(8));this.pA();break;case 1085:case 3:o9(this,new g.pC(9));break;case 1083:case 0:o9(this,new g.pC(2));this.H.stop();n9(this,this.i.getVideoData().lengthSeconds);break;case 1084:o9(this,new g.pC(4));break;case 2:o9(this,new g.pC(4));n9(this,u8(a));
break;case -1:o9(this,new g.pC(64));break;case -1E3:o9(this,new g.pC(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=A8(this.g).g;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.C=a,ora(this,a));a=A8(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.P.isActive()||this.QA()}else nra(this)};
g.h.My=function(){this.i.N("mdxpreviousnextchange")};
g.h.xn=function(){p9(this)||nra(this)};
g.h.nC=function(){this.g.Uu()};
g.h.ry=function(a){a&&(a=g.Iq("/watch_queue_ajax",{method:"GET",Cc:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.x)(this.qL,this)}))&&(this.M=(0,g.x)(a.abort,a))};
g.h.qL=function(a,b){var c=new g.aB(g.W(this.i),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.N("mdxautoplayupnext",c)};
g.h.Iy=function(a){isNaN(a)||this.i.N("mdxnowautoplaying",a)};
g.h.qy=function(){this.i.N("mdxautoplaycanceled")};
g.h.GF=function(a,b){-1==A8(this.g).playerState?r9(this,a):b&&this.g.seekTo(a)};
g.h.QA=function(){if(p9(this)){var a=A8(this.g);this.l.La(this.O);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.O=this.l.K(this.i,"onVolumeChange",this.Ey)}};
g.h.pA=function(){this.o.stop();if(!this.g.ea()){var a=A8(this.g);1==a.playerState&&o9(this,new g.pC(8));n9(this,u8(a));this.o.start()}};
g.h.qA=function(){this.A.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.A.start()};g.t(s9,g.V);s9.prototype.o=function(){G5("mdx-privacy-popup-cancel");this.l.hide()};
s9.prototype.A=function(){G5("mdx-privacy-popup-confirm");this.l.hide()};g.t(t9,g.V);t9.prototype.u=function(a){qra(this,a.state)};g.t(u9,g.NT);u9.prototype.I=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.F=g.tb(a,this.A,this),g.OT(this,(0,g.ge)(a,this.A)),a=this.l.getOption("remote","currentReceiver"),this.re(this.A(a)),this.enable(!0)):this.enable(!1)};
u9.prototype.A=function(a){return a.key};
u9.prototype.qe=function(a){return"cast-selector-receiver"==a?"Cast...":this.F[a].name};
u9.prototype.Hc=function(a){g.NT.prototype.Hc.call(this,a);this.l.setOption("remote","currentReceiver",this.F[a]);this.o.ib()};g.t(v9,g.IK);g.h=v9.prototype;
g.h.create=function(){gra(g.Jy(g.W(this.player)));this.l.push(g.Sp("yt-remote-before-disconnect",this.gI,this));this.l.push(g.Sp("yt-remote-connection-change",this.tK,this));this.l.push(g.Sp("yt-remote-receiver-availability-change",this.Ny,this));this.l.push(g.Sp("yt-remote-auto-connect",this.rK,this));this.l.push(g.Sp("yt-remote-receiver-resumed",this.qK,this));this.l.push(g.Sp("mdx-privacy-popup-confirm",this.RL,this));this.l.push(g.Sp("mdx-privacy-popup-cancel",this.QL,this));this.Ny()};
g.h.load=function(){this.player.cancelPlayback();g.IK.prototype.load.call(this);this.u=new m9(this,this.player,this.g);var a=(a=mra())?a.currentTime:0;var b=h9()?new z8(d9(),void 0):null;0==a&&b&&(a=u8(A8(b)));0!=a&&this.Jc(a);pra(this,this.jk,this.jk);g.NX(this.player.app,6)};
g.h.unload=function(){this.player.N("mdxautoplaycanceled");this.o=this.i;g.sf(this.u,this.g);this.g=this.u=null;g.IK.prototype.unload.call(this);g.NX(this.player.app,5)};
g.h.T=function(){g.Tp(this.l);g.IK.prototype.T.call(this)};
g.h.Ye=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.u.mx.apply(this.u,[a].concat(g.ea(c)))};
g.h.getAdState=function(){return this.Km};
g.h.bD=function(){return this.loaded?this.u.suggestion:null};
g.h.Ke=function(){return this.g?A8(this.g).Ke:!1};
g.h.hasNext=function(){return this.g?A8(this.g).hasNext:!1};
g.h.Jc=function(a,b){this.H=a||0;this.player.N("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.H};
g.h.getProgressState=function(){var a=A8(this.g),b=this.player.getVideoData();return{allowSeeking:g.P(g.W(this.player).experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.ac():!a.isAdPlaying()&&this.player.ac(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.l+s8(a):a.l,isAtLiveHead:1>=(a.u?a.i+s8(a):a.i)-this.getCurrentTime(),loaded:a.F,seekableEnd:a.u?a.i+s8(a):a.i,seekableStart:0<a.o?a.o+
s8(a):a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.Cn=function(){this.g&&this.g.Cn()};
g.h.gI=function(a){1==a&&(this.D=this.g?A8(this.g):null)};
g.h.tK=function(){var a=h9()?new z8(d9(),void 0):null;if(a){var b=this.o;this.loaded&&this.unload();this.g=a;this.D=null;b.key!=this.i.key&&(this.o=b,this.load())}else g.rf(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.D)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,u8(a)));this.player.N("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.Ny=function(){this.A=[this.i].concat(ira());var a=e9()||this.i;w9(this,a);this.player.la("onMdxReceiversChange")};
g.h.rK=function(){var a=e9();w9(this,a)};
g.h.qK=function(){this.o=e9()};
g.h.RL=function(){this.C=!0;k9=!1;l9&&g9(l9,1);l9=null};
g.h.QL=function(){this.C=!1;w9(this,this.i);this.o=this.i;k9=!1;l9=null;this.player.playVideo()};
g.h.uc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.A;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?o8():w9(this,b)),this.loaded?this.o:this.i;case "quickCast":return 2==this.A.length&&"cast-selector-receiver"==this.A[1].key?(b&&o8(),!0):!1}};
g.h.Fs=function(){this.g.Fs()};
g.h.Kb=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.dV.remote=v9;})(_yt_player);
